### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Gweiqi** [Chaste/Chaste#10]
Dear developers.

**I'm having some problems with the installation of chaste. My Ubuntu version is 20.04 LTS and I installed it using the Ubuntu package as described in "https://chaste.cs.ox.ac.uk/trac/wiki/InstallGuides/UbuntuPackage". I installed Chaste using the Ubuntu package as described in "" and did not encounter any errors at this step. Then I compiled as described in "https://chaste.cs.ox.ac.uk/trac/wiki/ChasteGuides/CmakeFirstRun" and in the configuration step I got the following message：**
 _"__-- Configuring done
 -- Generating done
-- Build files have been written to: /path/to/chaste_build__ "_ 
**without any errors.
But when I perform the build step, I type "make -j4 Continuous" and I get the following error：**

_gwqsz@gwqsz-VirtualBox:~/chaste/chaste_build$ make -j4 Continuous
Scanning dependencies of target timekeeper
Scanning dependencies of target testglobal
Scanning dependencies of target testmesh
Scanning dependencies of target testode
[  0%] Building CXX object global/CMakeFiles/timekeeper.dir/src/timekeeper.cpp.o
[  0%] Building CXX object global/test/CMakeFiles/testglobal.dir/ForTestArchiving.cpp.o
[  0%] Building CXX object mesh/test/CMakeFiles/testmesh.dir/data/inputs/gen2Dele.cpp.o
[  0%] Building CXX object ode/test/CMakeFiles/testode.dir/odes/ParameterisedCvode.cpp.o
[  1%] Linking CXX executable timekeeper
[  1%] Built target timekeeper
Scanning dependencies of target testpde
[  1%] Building CXX object pde/test/CMakeFiles/testpde.dir/pdes/SimpleUniformSourceParabolicPde.cpp.o
[  1%] Linking CXX static library libtestmesh.a
[  1%] Built target testmesh
Scanning dependencies of target testcell_based
[  1%] Building CXX object cell_based/test/CMakeFiles/testcell_based.dir/simulation/OffLatticeSimulationWithMyStoppingEvent.cpp.o
In file included from /usr/lib/petscdir/petsc3.12/x86_64-linux-gnu-real/include/petscis.h:7,
                 from /usr/lib/petscdir/petsc3.12/x86_64-linux-gnu-real/include/petscvec.h:9,
                 from /home/gwqsz/chaste/Chaste_source_code/pde/src/problem/AbstractLinearParabolicPde.hpp:46,
                 from /home/gwqsz/chaste/Chaste_source_code/pde/test/pdes/SimpleUniformSourceParabolicPde.hpp:42,
                 from /home/gwqsz/chaste/Chaste_source_code/pde/test/pdes/SimpleUniformSourceParabolicPde.cpp:36:
**/usr/lib/petscdir/petsc3.12/x86_64-linux-gnu-real/include/petscsys.h:169:6: error: #error "PETSc was configured with one OpenMPI mpi.h version but now appears to be compiling using a different OpenMPI mpi.h version"**
  169 | **#    error "PETSc was configured with one OpenMPI mpi.h version but now appears to be compiling using a different OpenMPI mpi.h version"**
      |      ^~~~~
In file included from /usr/lib/petscdir/petsc3.12/x86_64-linux-gnu-real/include/petscis.h:7,
                 from /usr/lib/petscdir/petsc3.12/x86_64-linux-gnu-real/include/petscvec.h:9,
                 from /home/gwqsz/chaste/Chaste_source_code/cell_based/src/cell/properties/CellVecData.hpp:44,
                 from /home/gwqsz/chaste/Chaste_source_code/cell_based/src/cell/Cell.hpp:49,
                 from /home/gwqsz/chaste/Chaste_source_code/cell_based/src/population/AbstractCellPopulation.hpp:39,
                 from /home/gwqsz/chaste/Chaste_source_code/cell_based/src/population/killers/AbstractCellKiller.hpp:39,
                 from /home/gwqsz/chaste/Chaste_source_code/cell_based/src/simulation/AbstractCellBasedSimulation.hpp:45,
                 from /home/gwqsz/chaste/Chaste_source_code/cell_based/src/simulation/OffLatticeSimulation.hpp:39,
                 from /home/gwqsz/chaste/Chaste_source_code/cell_based/test/simulation/OffLatticeSimulationWithMyStoppingEvent.hpp:39,
                 from /home/gwqsz/chaste/Chaste_source_code/cell_based/test/simulation/OffLatticeSimulationWithMyStoppingEvent.cpp:36:
/usr/lib/petscdir/petsc3.12/x86_64-linux-gnu-real/include/petscsys.h:169:6: error: **#error "PETSc was configured with one OpenMPI mpi.h version but now appears to be compiling using a different OpenMPI mpi.h version"**
  169 | #    **error "PETSc was configured with one OpenMPI mpi.h version but now appears to be compiling using a different OpenMPI mpi.h version"**
      |      ^~~~~
In file included from /home/gwqsz/chaste/Chaste_source_code/mesh/src/reader/GenericMeshReader.hpp:47,
                 from /home/gwqsz/chaste/Chaste_source_code/mesh/src/common/AbstractTetrahedralMesh.hpp:54,
                 from /home/gwqsz/chaste/Chaste_source_code/mesh/src/common/TetrahedralMesh.hpp:49,
                 from /home/gwqsz/chaste/Chaste_source_code/cell_based/src/population/AbstractCellPopulation.hpp:59,
                 from /home/gwqsz/chaste/Chaste_source_code/cell_based/src/population/killers/AbstractCellKiller.hpp:39,
                 from /home/gwqsz/chaste/Chaste_source_code/cell_based/src/simulation/AbstractCellBasedSimulation.hpp:45,
                 from /home/gwqsz/chaste/Chaste_source_code/cell_based/src/simulation/OffLatticeSimulation.hpp:39,
                 from /home/gwqsz/chaste/Chaste_source_code/cell_based/test/simulation/OffLatticeSimulationWithMyStoppingEvent.hpp:39,
                 from /home/gwqsz/chaste/Chaste_source_code/cell_based/test/simulation/OffLatticeSimulationWithMyStoppingEvent.cpp:36:
**/home/gwqsz/chaste/Chaste_source_code/mesh/src/reader/VtkMeshReader.hpp:55:10: fatal error: vtkDataArray.h: No such file or directory**
   55 | #include <vtkDataArray.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [cell_based/test/CMakeFiles/testcell_based.dir/build.make:63: cell_based/test/CMakeFiles/testcell_based.dir/simulation/OffLatticeSimulationWithMyStoppingEvent.cpp.o] **Error 1
make[2]: *** [CMakeFiles/Makefile2:11184: cell_based/test/CMakeFiles/testcell_based.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....**
[  1%] Building CXX object ode/test/CMakeFiles/testode.dir/odes/ParameterisedOde.cpp.o
[  1%] Linking CXX static library libtestglobal.a
[  1%] Built target testglobal
make[3]: *** [pde/test/CMakeFiles/testpde.dir/build.make:63: **pde/test/CMakeFiles/testpde.dir/pdes/SimpleUniformSourceParabolicPde.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:7748: pde/test/CMakeFiles/testpde.dir/all] Error 2
[  1%] Linking CXX static library libtestode.a
[  1%] Built target testode
make[1]: *** [CMakeFiles/Makefile2:1037: CMakeFiles/Continuous.dir/rule] Error 2
make: *** [Makefile:314: Continuous] Error 2_**

**I am a beginner and I really need your help.
Many thanks,
Guo Weiqi**

**Comment by mirams** [comment]
Is this a 'clean' Ubuntu 20.04 in a VirtualBox?

**Comment by mirams** [comment]
closing as no further info provided
