### ISSUE TITLE
Compilation error on Continuous case

### ISSUE THREAD

**Issue by ar-valdez** [Chaste/Chaste#11]
Hello there, I am new to the community.

I was trying to execute the first run case following the tutorial [web-page](https://chaste.cs.ox.ac.uk/trac/wiki/ChasteGuides/CmakeFirstRun). The building step succeeded without troubles, however, the compilation of Continuous failed, showing up the following error message

`Chaste/mesh/src/reader/VtkMeshReader.cpp:106:40: error: ‘virtual void vtkUnstructuredGrid::GetCellTypes(vtkCellTypes*)’ is deprecated: Please use GetDistinctCellTypesArray() instead. [-Werror=deprecated-declarations]
     mpVtkUnstructuredGrid->GetCellTypes(cell_types);
`

The VTK version I have installed is the following 9.1, Looking after your comments I salute you. 

Edit: If prompted I can edit the file that the compiler complains about but I'm afraid more trouble can appear... What current versions are you using?

**Comment by fcooper8472** [comment]
Hi @ar-valdez, we do not officially support VTK 9.x at the moment, although it is very much on our roadmap.

For now you have two options:

1. use an older version of VTK (v6.3+, v7.x, v8.x are all supported)
2. compile without treating warnings as errors (configure Chaste with `cmake -DChaste_ERROR_ON_WARNING=OFF`)

Please met me know if either of those work.

**Comment by ar-valdez** [comment]
Dear @fcooper8472,

Thanks for the answer, I was "suspecting that the problem" was in my VTK version.... (I needed to install the latest for other code)... I  am installing vtk 7.1.1 to give a try... I will let you know in this week...

Best regards.-

**Comment by ar-valdez** [comment]
Dear @fcooper8472,

I did install vtk 7.1, now I am getting a different error flag...

`[ 12%] Processing XML schema heart/src/io/ChasteParameters_1_1.xsd
/bin/sh: 1: /home/ar-valdez/xsd-4.0.0-x86_64-linux-gnu/bin: Permission denied
heart/CMakeFiles/chaste_heart.dir/build.make:443: recipe for target 'heart/src/io/ChasteParameters_1_1.cpp' failed
make[3]: *** [heart/src/io/ChasteParameters_1_1.cpp] Error 126
CMakeFiles/Makefile2:15704: recipe for target 'heart/CMakeFiles/chaste_heart.dir/all' failed
make[2]: *** [heart/CMakeFiles/chaste_heart.dir/all] Error 2
CMakeFiles/Makefile2:2768: recipe for target 'CMakeFiles/Continuous.dir/rule' failed
make[1]: *** [CMakeFiles/Continuous.dir/rule] Error 2
Makefile:420: recipe for target 'Continuous' failed
make: *** [Continuous] Error 2
`

I've downloaded the XSD, from [here](http://www.codesynthesis.com/download/xsd/4.0/linux-gnu/x86_64/xsd-4.0.0-x86_64-linux-gnu.tar.bz2) and generated the makefile pointing the location of the bin folder...

Do you have any suggestion on this issue?

**Comment by ar-valdez** [comment]
Dear @fcooper8472,

Let me share the solution I found. I installed Chaste using this [guide](https://chaste.cs.ox.ac.uk/trac/wiki/InstallGuides/UbuntuPackage)... After I did the installation with `cmake ..`  pointing to `vtk 7.1`...

make continuous worked fine, this is the test report:

100% tests passed, 0 tests failed out of 369

Label Time Summary:
Continuous_cell_based             = 897.78 sec*proc (96 tests)
Continuous_continuum_mechanics    =  25.15 sec*proc (11 tests)
Continuous_crypt                  = 169.95 sec*proc (29 tests)
Continuous_global                 =  28.89 sec*proc (34 tests)
Continuous_heart                  = 1200.20 sec*proc (75 tests)
Continuous_io                     =   2.54 sec*proc (6 tests)
Continuous_linalg                 =   3.66 sec*proc (10 tests)
Continuous_lung                   =  89.23 sec*proc (16 tests)
Continuous_mesh                   =  70.36 sec*proc (45 tests)
Continuous_ode                    =   4.13 sec*proc (15 tests)
Continuous_pde                    =  35.43 sec*proc (28 tests)
Continuous_python                 =   2.14 sec*proc (4 tests)

Total Test time (real) = 1273.17 sec


I believe I am ready to work with the library... Let me know your opinion @fcooper8472.

**Comment by fcooper8472** [comment]
Hi @ar-valdez, glad to hear you got it working!

Yes, if all the continuous tests pass you should be good to work with the library.

**Comment by ar-valdez** [comment]
Dear @fcooper8472,

I have one more question, no need to re-open this issue but I will write you here. My plan is to execute a code and not a test... The tutorials, concerning cell-based, are *.hpp files associated with the test cases.

I was reading your paper [text](https://doi.org/10.21105/joss.01848)... I've was expecting to run this [simulation case](https://chaste.cs.ox.ac.uk/trac/wiki/UserTutorials/RunningVertexBasedSimulations), but since the tutorial is a "test" I couldn't locate the output files associated to the cell-based...

That's all for now... Thanks

**Comment by fcooper8472** [comment]
Hi @ar-valdez, sorry I completely missed this!

Yes, simulations are generally run as "test" cases.  The test output is defined by the `CHASTE_TEST_OUTPUT` environment variable.  If this is not set, it will default (at least, on Linux) to `/tmp/$USER/testoutput`.
