### ISSUE TITLE
Extend CellData functionality to allow force classes not to require a target area modifier

### ISSUE THREAD

**Issue by AlexFletcher** [Chaste/Chaste#121]
In a vertex model simulation, if you use any of:

- `FarhadifarForce`
- `PlanarPolarisedFarhadifarForce`
- `NagaiHondaForce`
- `NagaiHondaDifferentialAdhesionForce`

then you *must* include a target area modifier in your simulation, as otherwise `AddForceContribution()` will throw the exception 

``
You need to add an AbstractTargetAreaModifier to the simulation in order to use a FarhadifarForce
``

when it tries to call `GetCellData()->GetItem("target area")` on each cell. 

To get around this, we introduced a `ConstantTargetAreaModifier` class for cases where we don't actually want the target area to grow over time, such as in simulations of germband extension (see [Tetley et al (2016)](https://doi.org/10.7554/eLife.12094) and [Finegan et al (2019](https://doi.org/10.1371/journal.pbio.3000522)) for related publications).

However, it would be nicer if we didn't have to explicitly provide a target area modifier unless we wanted to actually modify the target area. Instead, we could check if cells contained a target area data item, and if not, then use a default (settable) value for this.

This stems from the lack of a function like the following in `CellData`, which would be helpful in allowing us to check whether cells in a simulation have a certain cell data item without throwing an exception:

```
bool CellData::HasItem(const std::string& rVariableName) const
{
    /*
     * Note that mCellData[rVariableName] is not const. If rVariableName is not
     * a key, then mCellData[rVariableName] will create a new item in the map
     * and increase the size by one.  Using a const_iterator ensures that the
     * map remains const.
     */
    std::map<std::string, double>::const_iterator it = mCellData.find(rVariableName);
    if (it == mCellData.end())
    {
        return false;
    }
    return true;
}
```

Does anyone object to this function being added to `CellData`, assuming it passes tests etc? If no-one objects, then the tasks are to (i) implement this functionality and then (ii) streamline the vertex model code to avoid an exception being thrown as described above.

**Comment by jmosborne** [comment]
When I've don't this in the past I've used 
`cell_population.SetDataOnAllCells("target area", 1.0);`
Or in the cell vector construction. As then it's clear from the test what the target area is.

But I have no issues with you adding the HasItem method.
