### ISSUE TITLE
Get ready for (and make) a new release

### ISSUE THREAD

**Issue by jmpf** [Chaste/Chaste#125]
Of primary importance we need to have release notes ready for a new release.

We should probably have new versions of 

- https://chaste.cs.ox.ac.uk/trac/wiki/ReleaseNotes
- https://chaste.cs.ox.ac.uk/trac/wiki/LatestNews
- https://chaste.cs.ox.ac.uk/trac/wiki/ChasteAdmin/MakingARelease

**Comment by jmpf** [comment]
"latest news" has been removed from https://chaste.github.io  and replaced with [release notes](https://chaste.github.io/release-notes/release-notes/) and [changes since last release](https://chaste.github.io/release-notes/changes-since-last-release/).  The first of these will be populated with **all** previous/current releases as markdown.  The second will form the prototype for the next release.

**Comment by jmpf** [comment]
[release notes](https://chaste.github.io/release-notes/release-notes/) now populated from old wiki archive markdown.[changes since last release](https://chaste.github.io/release-notes/changes-since-last-release/) populated with template stub.

**Comment by mirams** [comment]
We should make a checklist of tickets that we'd like to get finished to do this:
e.g. new dependencies for latest Ubuntu?, working doxygen to go with it?

I think this could be before website finalising. Then maybe we hold off advertising until the new website is clean and tidy

**Comment by mirams** [comment]
> [release notes](https://chaste.github.io/release-notes/release-notes/) now populated from old wiki archive markdown.[changes since last release](https://chaste.github.io/release-notes/changes-since-last-release/) populated with template stub.

these links seem to be 404 errors now

**Comment by mirams** [comment]
Script to archive trac wiki pages to go with release: https://github.com/Chaste/infrastructure-scripts/blob/main/CreateStaticWikiPages.py which needs updating for new website and github wiki.

It used to archive everything in `sections = ['UserTutorials', 'ChasteGuides', 'InstallGuides', 'GettingStarted', 'ReleaseNotes']`

**Comment by fcooper8472** [comment]
@mirams @AlexFletcher @kwabenantim @jmpf @MILeach 

Check release notes related to:

- [x] #153 
- [x] #138 
- [x] #131 
- [x] #147 
- [x] #126 
- [x] #120 
- [x] #108 
- [x] #104 
- [x] #99 
- [x] #80 
- [x] #67 
- [x] #56 
- [x] #45 
- [x] #23 
- [x] #13 
- [x] #12 
- [x] #8 

Release notes are on a branch here: https://github.com/Chaste/Chaste.github.io/issues/50

**Comment by jmpf** [comment]
Pull requests have been reviewed.  Major ones have been documented.  Some were already in the release notes, but most were not.  See https://github.com/Chaste/Chaste.github.io/issues/50

**Comment by fcooper8472** [comment]
I'm making a new "making a release" page on the developer wiki, here:
https://github.com/Chaste/developer_wiki/wiki/Making-a-release

Currently it's just a wholesale copy of the old trac version, but I will begin updating it now.

**Comment by fcooper8472** [comment]
We made a new relesae.
