### ISSUE TITLE
Automate generating archive with appropriate boost version for TestArchiveFormat

### ISSUE THREAD

**Issue by jmosborne** [Chaste/Chaste#127]
In order to generate the archive for TestArchiveFormat we need to run something like 

`
cmake -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=/path/to/boost1.58 -DChaste_USE_CVODE=OFF /path/to/Chaste
`

So far i have 

* Set up a new docker 
* `docker build -t chaste:develop --build-arg TAG=develop https://github.com/chaste/chaste-docker.git`
* `docker run -it --init --rm -v chaste_data:/home/chaste -v $(pwd)/testoutput:/home/chaste/testoutput chaste:develop`

Installed boost 1.58 in the docker terminal

* `wget http://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2`
* `for f in *bz2; do tar -jxf $f; done`
*`cd ~/boost_1_58_0/`
* `./bootstrap.sh --prefix=$HOME/boost_1_58 && ./b2 -j 10 install`

Then try to config with 

* `cmake -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=/home/chaste/boost_1_58 -DBoost_NO_SYSTEM_PATHS=ON -DBoost_NO_BOOST_CMAKE=ON -DBoost_NO_SYSTEM_PATHS=O -DBoost_DEBUG=ON -DChaste_USE_CVODE=OFF ../src`

**Comment by fcooper8472** [comment]
@jmosborne just hijacking this issue: I'll edit the title and add some thoughts below, because I think there's a solution that doesn't involve docker.

**Comment by fcooper8472** [comment]
I have created a workflow here:
https://github.com/Chaste/Chaste/blob/develop/.github/workflows/regenerate-archive.yml

This has a "workflow_dispatch" trigger, which means you can run it from the GitHub UI, and you can select a specific branch to run it on.

Go to 

> Actions > Regenerate archive ([link](https://github.com/Chaste/Chaste/actions/workflows/regenerate-archive.yml))

and you will see a banner with "This workflow has a workflow_dispatch event trigger." and a dropdown box labelled "Run workflow".  Select your branch from that dropdown and click "Run workflow".

Once the workflow has finished running, you will be able to download a zip file containing the new archive files from the user interface for that specific workflow run.

Once a run has actually finished, I'll create a wiki page with some screenshots to illustrate.

**Comment by fcooper8472** [comment]
@kwabenantim this workflow currently uses `chaste/runner:jammy.portability-01`, so the only limitation is that this runner is always using <= oldest supported boost (which it currently is).

We could potentially create a specific runner for building these archives, but that might be overkill. What do you think?

**Comment by kwabenantim** [comment]
@fcooper8472, maybe we could add an extra tag to the portability image that has the oldest supported boost like `chaste/runner:oldest-boost` or something similar.

**Comment by kwabenantim** [comment]
@fcooper8472, the `chaste/runner:oldest-boost` tag is now available on [dockerhub](https://hub.docker.com/layers/chaste/runner/oldest-boost/images/sha256-d946b422e51840f5d50fe9b3a1861cfa8dba881c9fecc2a4585c182b5080f1b6?context=explore)

**Comment by fcooper8472** [comment]
The instructions for regenerating the archive are here:
https://github.com/Chaste/developer_wiki/wiki/Regenerate-Crypt-archive

**Comment by jmosborne** [comment]
I can confirm this worked a treat for regenerating the archive for PR 13. I would say that as it doesn't need to be done much i dont think you need a separate runner just use the oldest boost one.

**Comment by fcooper8472** [comment]
This is complete and documented. Closing.
