### ISSUE TITLE
Move Svn (Trac/data/re-directions) onto new server

### ISSUE THREAD

**Issue by jmpf** [Chaste/Chaste#133]
Subtask of #39

**Comment by jmpf** [comment]
I installed trac (which pulled in apache2 and libsvn ) on 23 May 2023.  Apache working and tested, but trac needed some thinking about.

**Comment by jmpf** [comment]
**Cloning SVN data**
```
# As svn@chaste (which has permission to use mount /var/www on large drive)
 svnadmin dump /var/svn/chaste/ > /var/www/chaste.svn_dump
```
(That takes about an hour)

```
# On newchaste.cs
sudo apt install subversion
sudo mkdir /home/svn
sudo useradd svn -g www-data -d /home/svn

# As svn@newchaste
scp chaste@chaste:/var/www/chaste.svn_dump .
```
**Failed** The server has 100Gb of root SSD (total).  This file is about 53 Gb

**Comment by jmpf** [comment]
Updated logical volume from 100Gb to 500Gb.

```
sudo lvresize --size 500G ubuntu-vg/ubuntu-lv
sudo resize2fs /dev/mapper/ubuntu--vg-ubuntu--lv 
```

**Comment by jmpf** [comment]
Set up the Subversion server on the new machine:
```
sudo mkdir /var/svn
sudo chown svn /var/svn 
sudo su - svn
svnadmin create /var/svn/chaste
svnadmin load /var/svn/chaste < /home/github/chaste.svn_dump
```

**Comment by jmpf** [comment]
```
# As svn@chaste:
trac-admin /opt/tracdb/chaste/ hotcopy chaste-hotcopy
```
```
# On newchaste
mkdir /opt/tracdb
sudo mkdir /opt/tracdb
sftp -r chaste@chaste:/home/svn/chaste-hotcopy .

# sudo su - svn
cp -r /home/github/chaste-hotcopy/ /opt/tracdb/
# Don't do the next line yet.  We might need to initialise first...
mv /opt/tracdb/chaste-hotcopy/ /opt/tracdb/chaste
```
Now need to work out what it takes to get trac-admin to work...

**Comment by jmpf** [comment]
Read https://trac.edgewall.org/ticket/13404 and so I patched the Ubuntu Trac distribution
```
--- /usr/lib/python3/dist-packages/trac/util/presentation.py.0  2023-08-11 14:59:47.877759479 +0000
+++ /usr/lib/python3/dist-packages/trac/util/presentation.py    2023-08-11 15:00:29.297810382 +0000
@@ -23,7 +23,11 @@
 
 from jinja2 import Markup, Undefined, contextfilter, evalcontextfilter
 from jinja2.filters import make_attrgetter
-from jinja2.utils import soft_unicode
+#from jinja2.utils import soft_unicode
+try:
+    from jinja2.utils import soft_unicode
+except:
+    from markupsafe import soft_str as soft_unicode

```

trac-admin now doesn't bail immediately...

**Comment by jmpf** [comment]
```#As svn@newchaste (with /opt/tracdb/chaste empty)
trac-admin /opt/tracdb/chaste/ initenv
```

**Comment by jmpf** [comment]
Apache needs to run as the same user as trac/svn:
```diff -u /etc/apache2/envvars~ /etc/apache2/envvars
--- /etc/apache2/envvars~       2023-03-01 22:43:55.000000000 +0000
+++ /etc/apache2/envvars        2023-08-16 08:32:20.760905195 +0000
@@ -13,7 +13,7 @@
 # Since there is no sane way to get the parsed apache2 config in scripts, some
 # settings are defined via environment variables and then used in apache2ctl,
 # /etc/init.d/apache2, /etc/logrotate.d/apache2, etc.
-export APACHE_RUN_USER=www-data
+export APACHE_RUN_USER=svn
 export APACHE_RUN_GROUP=www-data
```

**Comment by jmpf** [comment]
Copied /etc/apache2/sites-enabled/default.conf from chaste.cs and commented out enough of it so that the apache2 service could be started (without complaining that it didn't know about certain files.

**Comment by jmpf** [comment]
```
sudo trac-admin /opt/tracdb/chaste deploy /opt/tracdb/web
sudo chown -R svn:www-data /opt/tracdb/web/
```

**Comment by fcooper8472** [comment]
Data:
/var/www/chaste/downloads/data/

**Comment by jmpf** [comment]
> Data: /var/www/chaste/downloads/data/

Has this been copied?  Is it important?

**Comment by jmpf** [comment]
Don't bother with Trac, since we have a new wiki and a copy of the old Trac

Still todo:

- [x] A redirect for all newchaste pages to https://chaste.github.io/redirect (or similar)
- [x] Populate https://chaste.github.io/redirect see https://github.com/Chaste/Chaste.github.io/issues/84
- [x] Get IT to move the name chaste.cs to newchaste's IP and take it out of the firewall
- [x] Get SVN working on newchaste so that public and private projects can be viewed after redirect and sort out authentication on a basis of need (or move  public svn projects to github)
- [x] Scrap old server
- [x]  Move all public svn projects to github
- [x] Exceptional redirects from https://chaste.cs.ox.ac.uk/trac/wiki/PaperTutorials to an appropriate place, see https://github.com/Chaste/Chaste.github.io/issues/83 and todo list below

**Comment by jmpf** [comment]
Hard to test redirection because CS network is blocking requests from outside (even from Eduroam)

**Comment by jmpf** [comment]
On newchaste.cs this may work for redirecting some parts.  Still too hard to test from outside cs.
```
--- /etc/apache2/sites-available/000-default.conf.orig  2024-03-11 19:01:54.373090308 +0000
+++ /etc/apache2/sites-available/000-default.conf       2024-03-11 18:55:59.915428587 +0000
@@ -26,6 +26,10 @@
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
+
+Redirect 301 /trac/svn  https://chaste.github.io/redirect-svn
+Redirect 301 /trac https://chaste.github.io/redirect
+
 </VirtualHost>

```

**Comment by jmpf** [comment]
Configure SSL for https:
```
sudo a2enmod ssl
# Add configuration to /etc/apache2/sites-available/000-default.conf
...
-<VirtualHost *:80>
+<VirtualHost *>
...
+	# SSL
+	SSLEngine on
+	SSLOptions +StrictRequire
+	SSLCertificateFile /etc/apache2/ssl/chaste.cs.ox.ac.uk.crt
+	SSLCertificateChainFile /etc/apache2/ssl/chaste.cs.ox.ac.uk.crt
+	SSLCertificateKeyFile /etc/apache2/ssl/server.key
...
# Copy chaste.cs.ox.ac.uk.crt and server.key across from chaste.cs.ox.ac.uk
```

**Comment by jmpf** [comment]
Svn not working yet.  So far this week I have:
```
# Get and configure Apache Subversion module
sudo apt install subversion subversion-tools libapache2-mod-svn
sudo a2enmod dav
sudo a2enmod dav_svn
# Get the permissions and password files
scp chaste@chaste:/etc/svn-access-file .
scp chaste@chaste:svn-auth-file .
sudo cp svn-a*-file /etc/

# Added to  /etc/apache2/sites-available/000-default.conf
+
+<Location /svn>
+		DAV svn
+		SVNParentPath /var/svn
+		AuthzSVNAccessFile /etc/svn-access-file
+		AuthType Basic
+		AuthName "Chaste developer website and repository."
+		AuthUserFile /etc/svn-auth-file
+		Require valid-user
+
+                #AuthBasicProvider file anon
+                #Anonymous_NoUserID off
+                #Anonymous_MustGiveEmail on
+                #Anonymous_VerifyEmail on
+                #Anonymous_LogEmail on
+                #Anonymous anonymous
+</Location>
+
```

It allows me to enter my old credentials, but does not show me a Subversion page.

**Comment by jmpf** [comment]
Update about server IP move.
On 21 March we switched chaste and newchaste over via having the DHCP records looking for the other MAC address, so that the new server is now outside the firewall on chaste.cs.  This did not go to plan.  Probably because the old server was configured to have a static IP rather than asking for the IP dynamically.  This mean that we could only have one machine on chaste.cs at at time...
On 25 March I went to the machine room to reconfigure the old server but it was refusing to boot.  After two unsuccessful attempts we decided instead to pull the disk caddy out of the server.

**Comment by jmpf** [comment]
I collected my browser history for the old website so that I could group some categories for redirection:

- [x] https://chaste.cs.ox.ac.uk/buildbot/...  (old waterfall) redirect to ???
- [x] https://chaste.cs.ox.ac.uk/chaste/downloads (Chaste downloads) redirect to getting started: how to get the code
- [x] https://chaste.cs.ox.ac.uk/chaste/  (Any other old data) redirect to a suitable folder with anything we can recover in it
- [x] https://chaste.cs.ox.ac.uk/chaste/docs/... (Doxygen for release) redirect to doxygen for release
- [x] https://chaste.cs.ox.ac.uk/chaste/tutorials/...  (Tutorial for release) redirect to tutorials for release
- [x] https://chaste.cs.ox.ac.uk/public-docs/... (Doxygen for develop) redirect to Doxygen for develop
- [x] https://chaste.cs.ox.ac.uk/svn/chaste/projects/... (Subversion for bolt-on projects) Fix and redirect!
- [x] https://chaste.cs.ox.ac.uk/trac/browser/chaste/projects (Subversion interface for bolt-on projects) Fix and redirect!
- [x] https://chaste.cs.ox.ac.uk/trac/browser/chaste/trunk (Very old  Subversion repo interface) redirect to github repo
- [x] https://chaste.cs.ox.ac.uk/trac/browser/git_repo/ (Old git repo interface) redirect to github repo
- [x] https://chaste.cs.ox.ac.uk/trac Generic redirect
- [x] https://chaste.cs.ox.ac.uk/trac/admin Generic redirect
- [x] https://chaste.cs.ox.ac.uk/trac/ticket/... Redirect to Github archive of that Trac ticket
- [x] https://chaste.cs.ox.ac.uk/trac/timeline Generic redirect
- [x] https://chaste.cs.ox.ac.uk/trac/wiki/ Generic redirect
- [x] https://chaste.cs.ox.ac.uk/ Generic redirect
- [x] https://chaste.cs.ox.ac.uk/WebLab to https://scrambler.cs.ox.ac.uk
- [x] https://chaste.cs.ox.ac.uk/ActionPotential to https://cardiac.nottingham.ac.uk
- [x] http://chaste.cs.ox.ac.uk/WebLab to https://scrambler.cs.ox.ac.uk (redirect from advertised non-encrypted location)
- [x]  http://chaste.cs.ox.ac.uk/ActionPotential to https://cardiac.nottingham.ac.uk (redirect from advertised non-encrypted location)
- [x] Specific advertised links to paper tutorials (see other todo list above)

**Comment by jmpf** [comment]
Subversion server on new machine did not like repeated sections in configuration:
```
[Wed Mar 27 10:21:15.264539 2024] [authz_svn:error] [pid 11528:tid 140429543388736] [client 163.1.88.212:37450] Failed to load the mod_authz_svn config: Error while parsing config file: '/etc/svn-access-file': Section appears more than once in the authz file: [chaste:/projects/Plos2013]
```

Fixed this by commenting 3 redundant sections out of /etc/svn-access-file
```
chaste@chaste:~$ diff -u /etc/svn-access-file-orig /etc/svn-access-file 
--- /etc/svn-access-file-orig	2024-03-27 10:27:15.549027343 +0000
+++ /etc/svn-access-file	2024-03-27 10:32:57.233694726 +0000
@@ -282,8 +282,9 @@
 # (with non-standard access)
 
 # Working on the mythical executable paper...
-[chaste:/projects/Plos2013]
-geoff.williams@comlab.ox.ac.uk = r
+## jmpf 27/3/2024: chaste:/projects/Plos2013 appears public above
+## [chaste:/projects/Plos2013]
+## geoff.williams@comlab.ox.ac.uk = r
...
```

I can now get access via `svn co` or web-browser to https://chaste.cs.ox.ac.uk/svn/chaste/projects/ but it requires me to sign in with my old credentials.

**Comment by jmpf** [comment]
Looks like anonymous authentification needed a module.  In order to uncomment the Anonymous section in /etc/apache2/sites-available/000-default.conf
```
...
<Location /svn>
...
                AuthBasicProvider file anon
                Anonymous_NoUserID off
                Anonymous_MustGiveEmail on
                Anonymous_VerifyEmail on
                Anonymous_LogEmail on
                Anonymous anonymous
```

I simply needed:
`sudo a2enmod authn_anon `

**Comment by jmpf** [comment]
> > Data: /var/www/chaste/downloads/data/
> 
> Has this been copied? Is it important?

Looks like it hasn't been copied.  I need a SAS adapter before I can see if I can rescue data from the old drive.

**Comment by jmpf** [comment]
It may be that `/var/www/chaste' is no more.  The drive from the old server is refusing to be read and the HFS backup from it was deleted over Easter.  We may be missing some downloadable meshes and ancient bolt-on projects.

Searching on old machines and disks I found:
- Chaste logo
- Versions of the old "Oxford rabbit heart" mesh.

I put them at https://chaste.cs.ox.ac.uk/old-chaste-data/ but I don't know where to advertise this (if anywhere!).

**Comment by jmpf** [comment]
Recovered downloads folder from failing disk on old server: https://chaste.cs.ox.ac.uk/old-chaste-data/ 

Possibles to keep in a public repo (in order of importance):
1. Rabbit heart mesh https://chaste.cs.ox.ac.uk/old-chaste-data/downloads/data/
2. Old way to publish bolt-on projects https://chaste.cs.ox.ac.uk/old-chaste-data/downloads/projects/
3. Old related projects which we hosted https://chaste.cs.ox.ac.uk/old-chaste-data/downloads/related/

**Comment by jmpf** [comment]
Add redirects from port 80 to port 443 (on the same server) so if any old links are advertised as http then the server will 
1.  convert to https 
2. apply any https redirect rules as appropriate

```
<VirtualHost *:80>
# Redirect all plain http traffic to https on port 443
# Requires 
# sudo a2enmod rewrite
DocumentRoot /var/www/
RewriteEngine on
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}:443%{REQUEST_URI}
</VirtualHost>
```

**Comment by jmpf** [comment]
Top page redirection:
https://chaste.cs.ox.ac.uk/trac/wiki/PaperTutorials redirects to https://chaste.github.io/docs/paper-tutorials/

Most projects have a nasty lowercase mapping:
https://chaste.cs.ox.ac.uk/trac/wiki/PaperTutorials/Harvey2015 redirects to https://chaste.github.io/docs/paper-tutorials/harvey2015/

No deep links:
https://chaste.cs.ox.ac.uk/trac/wiki/PaperTutorials/Frontiers2014/CalculateRequiredTimesteps simply redirects to https://chaste.github.io/docs/paper-tutorials/frontiers2014/

Todo: What happened to HR2014, CellBasedComparison2016, PNAS_PopulationOfModels ?

**Comment by jmpf** [comment]
My attempts to redirect CellBasedComparison2016 and CellBasedComparison back to CellBasedComparison2017 were unsuccessful.  I can live with that.

**Comment by jmpf** [comment]
https://chaste.cs.ox.ac.uk/trac/wiki/PaperTutorials/HR2014 is referenced in https://www.heartrhythmjournal.com/cms/10.1016/j.hrthm.2015.05.027/attachment/9de70234-e040-4f5c-af48-0850fa66f5bf/mmc1.docx which is the supplementary to HR2015.  That is: the authors failed to anticipate the URL change.

**Comment by jmpf** [comment]
PNAS_PopulationOfModels did have an underscore but the new page does not.

**Comment by jmpf** [comment]
> PNAS_PopulationOfModels did have an underscore but the new page does not.

Fixed this.
