### ISSUE TITLE
Chaste docker: Automating multi-architecture build through GitHub actions

### ISSUE THREAD

**Issue by AlexFletcher** [Chaste/Chaste#136]
Automated multi-architecture builds of the `chaste/develop` docker image are failing with GitHub Actions - see branch [auto_docker_image](https://github.com/Chaste/Chaste/tree/auto_docker_image). (This multi-arch build was implemented due to requests for `arm64` images due mainly to the new mac hardware e.g. #43 but potentially also other Arm-based platforms.)

The GH runners are all `amd64`, so have to emulate `arm64` which is slow (building just for `amd64` is fine). When building from a clean `chaste/base` image, this failed due to running out of time (GH Actions have a 6 hour limit) e.g. see [this job](https://github.com/Chaste/Chaste/actions/runs/5201827234).

Subsequently, I (@bdevans) tried doing an incremental build based on the previous `chaste/develop` image to speed up the process, however that ran out of disk space - e.g. see [this job](https://github.com/Chaste/Chaste/actions/runs/5201827234).

Until GitHub rolls out `arm64` based runners (a [feature requested](https://github.com/actions/runner-images/issues/5631) for a while now), the only solution I can see is to build the multi-arch images on local hardware.

**Comment by AlexFletcher** [comment]
Question for @bdevans @fcooper8472 what sort of local hardware would be required? Do we need to find some money for this?

**Comment by bdevans** [comment]
It would need to be `amd64` with an up-to-date version of docker installed (so it can use `buildx` for multi-arch builds) and I think about 8GB RAM with I guess ~10GB disk space should be sufficient.

**Comment by fcooper8472** [comment]
I have a plan to repurpose one of the old Chaste build machines for this, which should be sufficient for the time being. Leave it with me for now...

**Comment by bdevans** [comment]
This is complete with PR #157.

**Comment by bdevans** [comment]
PR #157 has been merged and is working! 🥳
