### ISSUE TITLE
Create self-hosted GitHub runner to build docker images

### ISSUE THREAD

**Issue by fcooper8472** [Chaste/Chaste#143]
Related to #43 

@bdevans can create binaries for new macs, but automating this takes longer than the max job duration on GitHub hosted runners.

The plan is to repurpose lofty (machine in Oxford CS) to be a self-hosted runner.

todo:

- [x] Take lofty off all old buildbot duties [@fcooper8472]
- [x] Upgrade operating system to 22.04 [@fcooper8472]
- [x] Repair HFS backup software [@jmpf]
- [x] Install GitHub self-hosted runner [@fcooper8472]
- [x] Create GitHub workflow ready for new runner [@bdevans]

**Comment by jmpf** [comment]
Upgrade to 22.04 is stable and HFS (Spectrum Protect) is now working again.

I thought that I had already documented things that were dubious with the Lofty upgrade.  From my notes:
- libgoogleperf tools had to be removed for the 20.04 upgrade to succeed
- buildbot and python3-buildbot had to be removed for the 20.04 upgrade to succeed
- ssh configuration was reset to repository version (but there's a backup copy of the old one)

**Comment by bdevans** [comment]
This is complete with PR #157.

**Comment by bdevans** [comment]
PR #157 has been merged in and is working 🥳
