### ISSUE TITLE
HDF5 1.12 support

### ISSUE THREAD

**Issue by kwabenantim** [Chaste/Chaste#163]
This issue continues the discussion for legacy trac ticket 3063

---
@mirams created the following ticket on 2021-04-20 at 14:31:40, it is owned by @mirams
 
A major release that might have some substantial changes to address:
https://portal.hdfgroup.org/display/HDF5/Migrating+from+HDF5+1.10+to+HDF5+1.12

* **status:** new
* **type:** user story
* **priority:** normal
* **component:** heart
* **milestone:** Iteration 33
* **effort:** 16
* **effortexpended:** 0
* **initialeffort:** 16

---
Comment by @jmpf on 2022-07-06 at 15:13:21

When working on #37 I used the migration advice to make a hack to use old API. This may work.  Quick addition to `io/src/common/AbstractHdf5Access.hpp`:

```
+#define H5_USE_110_API
 #include <hdf5.h>
 #include <string>
```

**Comment by jmpf** [comment]
How do I do about adding a workflow to test this?  Should I amend one of the compatibility builds?

**Comment by kwabenantim** [comment]
The way @fcooper8472  handled it previously was by temporarily adding an extra build to the portability workflow on the branch, in this commit:  [3ec876cd](https://github.com/Chaste/Chaste/pull/152/commits/3ec876cd855b390961147c59f49b1b1b74301063). The `chaste/runner:jammy.portability-dev` now has HDF5 1.12.2 installed so should be okay for testing.

**Comment by kwabenantim** [comment]
@jmpf I pushed a couple of commits to the [issue_163_hdf5112](https://github.com/Chaste/Chaste/tree/issue_163_hdf5112) branch using the `H5_USE_110_API` solution.
