### ISSUE TITLE
PerMedCoE community benchmarking simulations

### ISSUE THREAD

**Issue by AlexFletcher** [Chaste/Chaste#166]
We should code up as many of the PerMedCoE community benchmarking simulations as possible in Chaste, and make sure that the code is running as quickly as it can (e.g. does the draft report give simulation timings based on compiling and running Chaste with the `DEBUG` flag?)

We should do this before our next chat with Arnau from PerMedCoE, which will be at **1pm on Thursday 5th October** (please email me if you don't already have the zoom link for this meeting and would like to join).

Folder of docs: 
https://drive.google.com/drive/u/0/folders/1xCSDrqjYnWVJqIcJ_oXeOJqlpf_wJleR

This contains Arnau's draft report with the results from December 2023: https://drive.google.com/drive/u/0/folders/1aQJvOwMsUCvLNRRKqM8nHadDV0KaZ9aQ

as well as the use cases descriptions: 
https://docs.google.com/document/d/1eroB1mOAt3asg63zwx6wcDGQbrkaFHd8/edit

The GitHub repo for the benchmarking simulations is: 
https://github.com/PerMedCoE/observatory_benchmark/tree/main

**Comment by bdevans** [comment]
It would be good to run the same benchmarks with docker on Linux, macOs and Windows to quantify the overhead too. 🐳

**Comment by MILeach** [comment]
Repo containing working code/results for the unit tests: [here](https://github.com/Chaste/PerMedCoE)

**Comment by mirams** [comment]
What's the current status of this? Bottlenecks or updates?

**Comment by fcooper8472** [comment]
Alex is waiting to hear back from Arnau with clarifications/answers to the questions we had

**Comment by AlexFletcher** [comment]
Just chased Arnau.

**Comment by AlexFletcher** [comment]
Here are the questions I sent Arnau and Thalia (in italics), along with their response.

_General_:

 _- One way to help minimise ambiguity in the unit tests would be to ask for the Physicell code to be uploaded to the github repo, since Physicell results are included in more results figures than any other tool; of course, ideally, all tools would provide their code for each unit test. Please can this code be uploaded?_

1. The PhysiCell code is already uploaded in the github (https://github.com/PerMedCoE/observatory_benchmark/tree/main/multiscale_benchmark/2022_09_hackathon/Physicell/Code) if you have any doubts on the initial configurations of the tests, you can find in the Physicell/Code/unit_tests folder the custom code and the config files. If you are not familiar, you need to be in the directory Physicell/Code/ and use the makefile to compile the according unit test for example:

  	$make fixed_cell_cycle

  	$make

 

_Cell Cycle - Fixed Duration:_

 _- Figure 2.1.2.b on page 14 of the benchmarking report (https://drive.google.com/file/d/1bgpD29n1Wr-scJkfA8KehB2m3UyFOBeB/view?usp=drive_link) does not reflect the Chaste results recorded in the github repo (https://github.com/PerMedCoE/observatory_benchmark/blob/main/multiscale_benchmark/2022_09_hackathon/Chaste/unit_test_cellcycle/results/cellcycle_fixed.png). Please can you update this?_

We have updated the figure and you can check the new one here: [https://github.com/PerMedCoE/observatory_benchmark/tree/main/multiscale_benchmark/2022_09_hackathon/analysi](https://github.com/PerMedCoE/observatory_benchmark/tree/main/multiscale_benchmark/2022_09_hackathon/analysis)s/fixed_cell_cycle_volumes.png


_Cell Cycle - Stochastic Duration:_

 _- Similar issue to that above re: figure results._

We have updated these figures: https://github.com/PerMedCoE/observatory_benchmark/tree/main/multiscale_benchmark/2022_09_hackathon/analysis/stohastic_cell_cycle_volumes.png


 _- Please clarify whether the cell cycle phase durations should be independent random variables._

We are not sure what you mean here by independent random variables. The point is that each phase should have a 10% duration variability independently of the duration of previous/following phases.


 _- The results seem to be based on a single stochastic simulation performed with each tool. To improve comparison across tools, we suggest that summary statistics instead be plotted, e.g. mean +/- standard deviation, based on say 10 simulations._

I get your point. We’ll contact the rest of the teams to check if they are able/willing to do this. Nevertheless, in such a summary statistic and if all the tools use the same stochastic distribution, the mean should coincide with the fixed duration.


_Diffusion - Single Cell Sink:_

 _- The unit test specification does not unambiguously define the initial condition. Should c(x, 0) be 10 everywhere in the domain, 0 everywhere in the domain, or 10 everywhere in the domain except at the very centre?_ 

You have 10 concentration units everywhere in the domain except in the centre where you have a sink.


_What is the spatial extent of the sink term?_ 

Good question. We have a cell radius of 5 um in PhysiCell, but point sink should be fine because of the discretisation of the domain (see next question).


_What discretization is required in the case of FEM? These aren't clear as currently described._

You can have 3 regularly distributed samples per side. In PhysiCell, we have 3 voxels per side in our FVM: 60 um of side divided in 3 voxels of 20 um. You can see this in the PhysiCell png: https://github.com/PerMedCoE/observatory_benchmark/blob/main/multiscale_benchmark/2022_09_hackathon/Physicell/output/diffusion/diff_timepoint0.png 


 _- There is no definition of \lamba (= 20uM/0.01min) in the unit test - what is this parameter? It might be helpful to spell out the unit test mathematically._

Lamba is the cell’s uptake rate, how much substrate it’s eating up per unit of time.

I agree that a thorough mathematical description would benefit the description of the tests.


_Diffusion - 1k Cells as Sinks:_

_- Similar issues to that above._

In this case we work with a bigger box of 34560 um box. In PhysiCell, we have 12 voxels cube for a total 1728 voxels. In your case, you could have 12 samples per side.


_Mechanics - Movement of a Cell with Friction:_

 _- Figure 2.1.2.e on page 17 of the benchmarking report (https://drive.google.com/file/d/1bgpD29n1Wr-scJkfA8KehB2m3UyFOBeB/view?usp=drive_link) seems to be a plot of velocity against time, not distance moved against time as claimed. Please can you double check this?_

We will update this figure accordingly, these are preliminary results, we need to check the PhysiCell results. But, I will let you know as soon as possible when I upload the correct figure of this unit test.

**Comment by MILeach** [comment]
# Current chaste unit test status

- [x] Cell Cycle - Fixed Duration
- [x] Cell Cycle - Stochastic
- [x] Diffusion - Single Cell (In progress - Fergus)
- [x] Diffusion - 1000 Cells (In progress - Fergus)
- [x] Mechanics - Cell With Friction
- [x] Mechanics - Two Cells Pushing Each Other
- [ ] One Cell With Chemotaxis (In progress - Fergus)

# Further Questions

## Diffusion
- Output summary equations are not quite clear. They appear to only differ in the coefficient (1/1728 vs Vvoxel)

## Diffusion - 1000 
- Still a little uncertain around the 12x12x12 box when we have 1000 cells (10x10x10)

## Chemotaxis
- What is the coefficient for the correlation between chemical gradient and movement?
- What are the boundary conditions for the edges of the box?
- Which concentration data should be output?
- Should the position output be (x, y, z) or a distance from the source etc?

# To Do 
- [ ] Fergus to update diffusion tests and implement chemotaxis test
- [ ] Matt and Jack to make a start on use cases. Use [this](https://chaste.cs.ox.ac.uk/trac/wiki/PaperTutorials/CellBasedComparison2017) as a starting point. Physicell [reference code](https://github.com/PerMedCoE/observatory_benchmark/tree/main/multiscale_benchmark/2022_09_hackathon/Physicell/Code/use_cases)

**Comment by fcooper8472** [comment]
### Diffusion questions:

[here](https://github.com/PerMedCoE/observatory_benchmark#diffusion-of-molecules-one-cell-as-sink) it clearly states:

> "Initial condition: c(x,t=0)=0 inside the simulation domain."

But in the response it clearly states:

> "You have 10 concentration units everywhere in the domain except in the centre where you have a sink."

These appear to directly contradict each other. Which should we be using?

**Comment by mirams** [comment]
Maybe worth starting a few clarifying "issues" on https://github.com/PerMedCoE/observatory_benchmark ?

**Comment by AlexFletcher** [comment]
I'm pasting an email from Thalia Diniaco from PerMedCoE on 20th Dec 2023:

thanks for providing the results. I have some questions regarding the newly added results.

In the unit test of the diffusion, where we have one cell acting as a sink I observed that you have negative values for the first timesteps of the simulation:

![unnamed](https://github.com/Chaste/Chaste/assets/2211699/5116908a-ad8b-497e-a7dd-d7fdfc53715e)

Are you sure you are using the correct dt for the diffusion? Is that expected behavior?

As far as the larger diffusion test with 1000 cells, the results you have provided is the average concentration? If not, could you upload the average concentration of all the voxels?


Going to the use case of the monolayer, I see that you have two different results, one with single cell, and one with multiple cells. Are you referring to the spheroid with the multiple cells?

Thanks a lot for taking the time to implement these. I would appreciate if you could clarify these questions so I can proceed in incorporating them in the draft of the paper.

**Comment by kwabenantim** [comment]
Follow-up from Arnau

**Chaste:**

1. Diffusion with 1k sinks:
    1. We are not sure of your resulting dynamic. The mean concentration should reach the equilibrium at 10 uM and yours goes to 4 and then relaxes to 2.
    2. Please confirm that your resulting values is the mean for ALL the voxels
2. Cells pushing:
    1. Please confirm that the distances are from the cells’ centres or from the cells’ surface

**Comment by kwabenantim** [comment]
> 2. Cells pushing:
>    
>    1. Please confirm that the distances are from the cells’ centres or from the cells’ surface

The distances are from the cell centres. The test uses `NodeBasedCellPopulation` which is a centre-based cell population.

**Comment by jmosborne** [comment]
@fcooper8472 Ive looked at the Diffusion code. 
For 1 sink I think the differences can be due to the initial conditions (u=0) not matching the boundary conditions (u=10) and differing interpretations of voxels and nodes.  Is there a copy of the concentration timeseries plot as the only one i could fins is in  Fig 2.1.3 of https://docs.google.com/document/d/1LHle7zrSg1kKXnR0nRhytr5v0B3NpBRi/edit and both of the solutions in here are wrong! The Physicell one deosnt look to have a sink and the bidynamo one is the wrong initial condition. The one above looks possible but is that rescalled? 

For the 1000 sinks I cant find the code.

**Comment by jmosborne** [comment]
I solved the -ve issue by implementing consistent initial/bounday conditions. Solution at central voxel goes up monotonically to 9.6 (which was the steady state before) so looks like the figure above but with no -ve part. If the results in the figure above are u*600 then chaste is the only correct one!

**Comment by jmosborne** [comment]
Wont let me push to repo is this a me issue (probably) or a setting on the repo.

**Comment by fcooper8472** [comment]
Thanks @jmosborne !

The code for both is here:
https://github.com/Chaste/PerMedCoE/blob/master/test/unit_tests/TestDiffusion.hpp

`void Test12x12x12()` is the 1000 sink one (well, actually, might be 12^3).

You should also now have access to the repository - I've added access for the Developers team, which you're in.

**Comment by jmosborne** [comment]
I committed the changes for the 1 sink example in https://github.com/Chaste/PerMedCoE/commit/ee8da1ec47c85668aeeca4f987336b540395ae18

Where is the figure to add the results to, and the discussion? is it that online google doc or permedcoe github?

Heres my chaste result. 
![ChasteDifusion](https://github.com/Chaste/Chaste/assets/2212095/b427fe68-74e4-47af-9585-01cb214b9691)

I will look at the 1000 soon. (took a while to run!)

**Comment by mirams** [comment]
Any update on this @jmosborne , did your new results make it into the central PermedCoE repo?

**Comment by jmosborne** [comment]
I did submit both the 27 cell and 1000 cell models. The 1000 cells is quite different to the other codes but i think wre correct (well correct in how ive interpreted the model:)) It should be as different weights of cell sources are being used differntoly in the different codes, I made some edits to clarify this and I'm waiting on meeting Thalia. Ill see if they are at the SMB.

**Comment by jmosborne** [comment]
Met with Arnau and Thalia to discuss the PDEs and happy the differenc in PDEs is due to scaling Im going to solve it as pde on coontinuum domain as thats what were doing in chaste to demonstate an "exact solution". 
Things to do
* Look at Use case 2 Monlayer no diffusion as chaste sim is short at the meoment.
* Pde Solution for  the 1000 cell example (matlab PDE tool or similar) Add to doc. 
* Keep eye on document to check equations of models added correctly.

**Comment by jmosborne** [comment]
Ill try to look at the first 2 this week and the other one when they start posting the maths.

**Comment by jmosborne** [comment]
Fixed the monolayer no diffusion example in 
https://github.com/Chaste/PerMedCoE/commit/8a602e3c7a47a5b6fdd36cda90034e1d3e1e63d3
https://github.com/Chaste/PerMedCoE/commit/faa53effca1011db616ae3d642c7fd5aaf6367e2
https://github.com/Chaste/PerMedCoE/commit/ac43bf434647b4f1b757bf99a3d6b35c48d9787b

**Comment by jmosborne** [comment]
Also done the PDE with 1000 cells example.

**Comment by MILeach** [comment]
@jmosborne thanks for all your work on this!

Is there anything else you need from the rest of us with regards to this work, e.g. unit tests etc?

**Comment by jmosborne** [comment]
As far as I'm concerned were all squared away on the unit tests, we could do some of the stretch simulations i,e monolayer with PDE but these aren't done by many so propbably better to get what we do correct rather than stretch but happy to discuss.

**Comment by MILeach** [comment]
@jmosborne all sounds good, thank you! 

As this is wrapping up we're going to close the issue - if you need any help with anything feel free to re-open it. Appreciate the work you've put in to get these sorted out!
