### ISSUE TITLE
Disk space tests on GitHub actions

### ISSUE THREAD

**Issue by fcooper8472** [Chaste/Chaste#169]
@mirams and @bdevans have both seen the disk space test fail from a GitHub actions environment.

It appears that under certain circumstances less than 5Gb is listed as available.

This test is primarily to alert users to potential issues with their setup, and so it seems appropriate to skip this test in a GitHub actions environment.

**Comment by bdevans** [comment]
I agree that it's reasonable to skip the test for GH Actions. This will resolve the issue with PR #157.
