### ISSUE TITLE
Migrate how-to generation to GitHub

### ISSUE THREAD

**Issue by fcooper8472** [Chaste/Chaste#185]
There is an index of "how-tos" here:
https://chaste.cs.ox.ac.uk/trac/wiki/ChasteGuides/HowTo

These are generated from specially-formatted comments in the source code of test files by a Python script in the infrastructure-scripts repository:

```
GenerateHowTo.py
```

It has been being run, as the wiki page was last updated in June, but it's unclear how. It's referenced in

```
run-doxygen.py
```

so it's possible it was generated with some Doxygen output. But, both scripts are Python 2 syntax, and we've not recently run anything with Python 2...

In any case, the best route forward is to re-write this as a new Python script that will generate a markdown file with the same information, and update a page on the github pages site, if necessary.

This is underway and this issue will be updated with progress.

**Comment by fcooper8472** [comment]
This is underway, with a new script in the `python/infra` directory:

e62d6653bf8909949fda3701d3e29fcfa9885bb5

**Comment by fcooper8472** [comment]
Not yet public on the menus, but this is now available here:
https://chaste.github.io/docs/how-tos/

@mirams does this look OK?

The only bug so far is I forgot the L in the line specification of the GitHub URL, so the links don't resolve to the correct line. But that will be fixed in an upcoming commit.

**Comment by mirams** [comment]
Yeah, functionally looking good. 

Presentation-wise a few improvements probably.

First one is just about the whole website I guess. Trac used to use horizontal space well (wiki could include line breaks if we wanted them). The text on the trac website isn't much smaller than the new website, but look how much more scrolling you need to do now.
<kbd><img width="1716" alt="image" src="https://github.com/Chaste/Chaste/assets/858776/7030e009-a61d-48a8-b6d2-d9f27957bed4"></kbd>

new one (when even the quick link side menu doesn't fit on the whole screen!):
<kbd><img width="1724" alt="image" src="https://github.com/Chaste/Chaste/assets/858776/189f613f-0180-42c6-8853-ad6e93278365"></kbd>

Other things are a couple of links can be added:
<kbd><img width="736" alt="image" border=1 src="https://github.com/Chaste/Chaste/assets/858776/7aa1baf1-8a03-47b6-8811-39f6e8294725"></kbd>
this bullet point had a link to doxygen class documentation and also wiki page on how to do Cellml to code. I guess these now could be just later updates to the comments to use new markdown link format if we don't want to do anything special.

Then the actual links to the test lines themselves look a bit weird as giant quotes (in bigger font size than the more important descriptions). In fact we could probably not show those at all and just have the whole bullet point description linking to that location?

The 'Uncategorised' can just be listed under the top level heading (e.g. directly under `#Continuum Mechanics`) you don't need to put "Uncategorised":
<kbd><img width="1236" alt="image" src="https://github.com/Chaste/Chaste/assets/858776/95768c06-9645-44a1-87c0-d65e241d4b30"></kbd>

**Comment by fcooper8472** [comment]
A combination of changes to the website and to Chaste have addressed all of your comments @mirams:

- horizontal space now used much better, with the main column now most of the page
- all how-tos have been updated on the Chaste end to link either directly to the old wiki page (until moved to the new website) or to the new location for the doxygen classes
- quotes have been replaced by sub-bullets
- uncategorised are now not labelled as such, and just appear at the top of each section

**Comment by fcooper8472** [comment]
Closed by #189
