### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by lolsenkettle** [Chaste/Chaste#253]
I am running cmake after accessing and installing the cmake dependencies. cmake /home/lolsenkettle/Louise\ Swinburne/CHASTE/Chaste/

However the following errors occur:

![Screenshot from 2024-04-11 10-41-40](https://github.com/Chaste/Chaste/assets/122413780/e1312e6e-918f-483c-a172-deee9b7bbd4f)
![Screenshot from 2024-04-11 10-41-24](https://github.com/Chaste/Chaste/assets/122413780/9dccd4e4-5d4a-4084-8087-9dbb5cb7aacc)

I tried reinstalling vtk and doing all the steps again but the same error occurs.

**Comment by fcooper8472** [comment]
Hi @lolsenkettle, I will need some more information to be able to help. It looks as though the problem is that HDF5 was not detected by CMake.

Can I ask:

1. Which operating system are you using?
2. Have you followed one of the install guides here: https://chaste.github.io/docs/installguides/ ?

**Comment by lolsenkettle** [comment]
I am trying to install on ubuntu 22.04.4 jammy version. I followed the instructions on this page: https://chaste.github.io/docs/installguides/ubuntu-package/

I installed latest version of chaste 2024.1. I then followed the instructions on this page: https://chaste.github.io/docs/user-guides/cmake-first-run/

These are the screenshots of the error message
![Screenshot from 2024-04-16 10-26-20](https://github.com/Chaste/Chaste/assets/122413780/32f903ef-56f1-47de-baf3-8eb5f6c495ec)
![Screenshot from 2024-04-16 10-26-08](https://github.com/Chaste/Chaste/assets/122413780/23343cbe-472f-47e0-8e43-a258faf115f6)
![Screenshot from 2024-04-16 10-25-51](https://github.com/Chaste/Chaste/assets/122413780/e32c4a6c-2db9-4698-8a5e-3f1b7eac7846)
![Screenshot from 2024-04-16 10-25-24](https://github.com/Chaste/Chaste/assets/122413780/b3613059-8c77-460b-ae9a-2ce2a36460ad)

**Comment by fcooper8472** [comment]
Hi @lolsenkettle, apologies for the delay on this.

If you have followed these steps of the installation instructions:

```
sudo apt update
sudo apt install chaste-dependencies
```

then you should have HDF5 installed in a standard location.

Just to verify that it is installed correctly, please could you run:

```
dpkg -l | grep hdf5
```

and reply with the output of that?

**Comment by lolsenkettle** [comment]
This is the output:

lolsenkettle@lolsenkettle-ThinkPad-L390:~$ sudo apt install chaste-dependencies
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
chaste-dependencies is already the newest version (2022.04.11).
0 to upgrade, 0 to newly install, 0 to remove and 7 not to upgrade.

lolsenkettle@lolsenkettle-ThinkPad-L390:~$ dpkg -l grep hdf5
dpkg-query: no packages found matching hdf5
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  grep           3.7-1build1  amd64        GNU grep, egrep and fgrep


THis is the output from sudo apt update:

sudo apt update
[sudo] password for lolsenkettle: 
Hit:1 http://au.archive.ubuntu.com/ubuntu jammy InRelease
Ign:2 https://chaste.github.io/ubuntu jammy/ InRelease                         
Hit:3 http://au.archive.ubuntu.com/ubuntu jammy-updates InRelease              
Hit:4 http://au.archive.ubuntu.com/ubuntu jammy-backports InRelease            
Hit:5 https://packages.microsoft.com/repos/ms-teams stable InRelease           
Hit:6 https://dl.google.com/linux/chrome/deb stable InRelease                  
Hit:7 https://chaste.github.io/ubuntu jammy/ Release                           
Get:8 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]               
Get:9 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]      
Hit:11 https://www.synaptics.com/sites/default/files/Ubuntu stable InRelease   
Hit:12 http://security.ubuntu.com/ubuntu focal-security InRelease              
Err:8 http://archive.ubuntu.com/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32
Get:13 http://archive.ubuntu.com/ubuntu bionic-security InRelease [102 kB]
Err:13 http://archive.ubuntu.com/ubuntu bionic-security InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [102 kB]
Err:14 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32
Reading package lists... Done
W: GPG error: http://archive.ubuntu.com/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32
E: The repository 'http://archive.ubuntu.com/ubuntu bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://archive.ubuntu.com/ubuntu bionic-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32
E: The repository 'http://archive.ubuntu.com/ubuntu bionic-security InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://archive.ubuntu.com/ubuntu bionic-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32
E: The repository 'http://archive.ubuntu.com/ubuntu bionic-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by lolsenkettle** [comment]
> Hi @lolsenkettle, I will need some more information to be able to help. It looks as though the problem is that HDF5 was not detected by CMake.
> 
> Can I ask:
> 
> 1. Which operating system are you using?
> 2. Have you followed one of the install guides here: https://chaste.github.io/docs/installguides/ ?

I am trying to install on ubuntu 22.04.4 jammy version. I followed the instructions on this page: https://chaste.github.io/docs/installguides/ubuntu-package/

I installed latest version of chaste 2024.1. I then followed the instructions on this page: https://chaste.github.io/docs/user-guides/cmake-first-run/

**Comment by mirams** [comment]
It looks as if something is strange with your operating system if you can't run 
`
sudo apt update
`
without errors - is it still producing the same ones above?

Did you definitely install the public key for the Chaste repo
`
sudo wget -O /usr/share/keyrings/chaste.asc https://chaste.github.io/chaste.asc
`
as per bottom of section 1: https://chaste.github.io/docs/installguides/ubuntu-package/ ?

**Comment by lolsenkettle** [comment]
Thanks I managed to follow the instructions on this page [https://chaste.github.io/docs/installguides/ubuntu-package/] and it is now working fine with Ubuntu 22.04:

Known issue affecting Ubuntu 22.04

Due to a change in libexpat that addresses a security vulnerability, VTK functionality is currently affected. This is a [known issue](https://bugs.launchpad.net/ubuntu/+source/expat/+bug/2058415) that cannot be easily addressed by Chaste.

If you are using Chaste on Ubuntu 22.04, a temporary workaround is to explicitly install and hold an older versions of libexpat:

sudo apt install libexpat1=2.4.7-1 libexpat1-dev=2.4.7-1
sudo apt-mark hold libexpat1 libexpat1-dev
