### ISSUE TITLE
Ubuntu 24.04 support

### ISSUE THREAD

**Issue by mirams** [Chaste/Chaste#257]
Official release on Thursday.

- [x] Update debs
- [x] update instructions on https://chaste.github.io/docs/installguides/ubuntu-package/ 
- [x] a GitHub workflow to run Chaste on 24.04
- [x] list any failures on here
- [x] Fix them all!
- [x] Update https://chaste.github.io/docs/installguides/dependency-versions/ 
  - https://github.com/Chaste/Chaste.github.io/pull/88
- [x] Make this new one the main testing environment and update portability builds
  - https://github.com/Chaste/dependency-modules/issues/68.

Dependency versions:
- [x] Boost 1.83
- [x] HDF5 1.10.10
- [x] Parmetis 4.0.3 (supported)
- [x] PETSc 3.19
- [x] Sundials 6.4.1
- [x] VTK 9.1.0 (supported)
- [x] Xerces-C 3.2.4 (supported)
- [x] XSD 4.0.0 (supported)

The default Python (3.12) is not yet supported by [Chaste codegen](https://github.com/ModellingWebLab/chaste-codegen/issues/281):
- [x] Python 3.12 support

Feel free to update list above @fcooper8472 @kwabenantim @ptheywood @jmpf

**Comment by bdevans** [comment]
When building the `chaste/develop` image from [`noble` branch](https://github.com/Chaste/chaste-docker/tree/noble) again with the latest `ubuntu:noble` image as a base, I get the following warnings which are set to error (so it fails):
```
[  1%] Generating Build Config and Version Info
-- Found Git: /usr/bin/git
-- Current Chaste Git Revision = f2ff7ee. Chaste Modified = false
-- updating buildtime...
CMake Warning (dev) at /home/chaste/src/cmake/Modules/ChasteGenerateVersionAndBuildInfo.cmake:89 (find_package):
Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
the cmake_policy command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

[  1%] Building CXX object global/CMakeFiles/chaste_global.dir/src/Citations.cpp.o
[  1%] Building CXX object global/CMakeFiles/chaste_global.dir/src/Debug.cpp.o
[  1%] Building CXX object global/CMakeFiles/chaste_global.dir/src/CommandLineArguments.cpp.o
[  1%] Building CXX object global/CMakeFiles/chaste_global.dir/src/Exception.cpp.o
[  1%] Building CXX object global/CMakeFiles/chaste_global.dir/src/ExecutableSupport.cpp.o
[  2%] Building CXX object global/CMakeFiles/chaste_global.dir/src/FileFinder.cpp.o
[  2%] Linking CXX static library libtestglobal.a
[  2%] Built target testglobal
[  2%] Building CXX object global/CMakeFiles/chaste_global.dir/src/GetCurrentWorkingDirectory.cpp.o
[  2%] Building CXX object global/CMakeFiles/chaste_global.dir/src/LogFile.cpp.o
[  2%] Building CXX object global/CMakeFiles/chaste_global.dir/src/MathsCustomFunctions.cpp.o
/home/chaste/src/global/src/ExecutableSupport.cpp:115:13: error: PETSC_NULL is deprecated, use PETSC_NULLPTR instead (since version 3.19) [-Werror]
115 |     PETSCEXCEPT(PetscInitialize(pArgc, pArgv, PETSC_NULL, PETSC_NULL));
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/chaste/src/global/src/ExecutableSupport.cpp:115:13: error: PETSC_NULL is deprecated, use PETSC_NULLPTR instead (since version 3.19) [-Werror]
[  2%] Building CXX object global/CMakeFiles/chaste_global.dir/src/OutputDirectoryFifoQueue.cpp.o
[  2%] Building CXX object global/CMakeFiles/chaste_global.dir/src/OutputFileHandler.cpp.o
[  2%] Building CXX object global/CMakeFiles/chaste_global.dir/src/PosixPathFixer.cpp.o
[  2%] Building CXX object global/CMakeFiles/chaste_global.dir/src/ProgressReporter.cpp.o
[  2%] Building CXX object global/CMakeFiles/chaste_global.dir/src/RandomNumberGenerator.cpp.o
[  2%] Building CXX object global/CMakeFiles/chaste_global.dir/src/TimeStepper.cpp.o
[  2%] Linking CXX static library libtestode.a
[  2%] Built target testode
[  2%] Building CXX object global/CMakeFiles/chaste_global.dir/src/Warnings.cpp.o
cc1plus: all warnings being treated as errors
make[2]: *** [global/CMakeFiles/chaste_global.dir/build.make:139: global/CMakeFiles/chaste_global.dir/src/ExecutableSupport.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  2%] Linking CXX static library libtestpde.a
[  2%] Built target testpde
make[1]: *** [CMakeFiles/Makefile2:3650: global/CMakeFiles/chaste_global.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Linking CXX shared library dynamic/libDynamicallyLoadableLr91.so
[  2%] Built target DynamicallyLoadableLr91
[  2%] Linking CXX static library libtestcell_based.a
[  2%] Built target testcell_based
make: *** [Makefile:166: all] Error 2
```

I have also tried building Chaste `2024.1` with `noble` and the tests get stuck at `TestVisualizingWithParaviewTutorial` (see #238). A few other tests also currently fail.

**Comment by bdevans** [comment]
After turning off `Chaste_ERROR_ON_WARNING` and building the latest code from `develop` on the `noble` base image, then running the `Continuous` tests with 1 core, I get the following:
```
Total Test time (real) = 614.76 sec

The following tests FAILED:
          3 - TestCitations (Failed)
         78 - TestQuadraticMesh (Failed)
         93 - TestVtkMeshReader (Subprocess aborted)
        113 - TestXmlMeshWriters (Failed)
        175 - TestHdf5Converters (Subprocess aborted)
        190 - TestCompressibleNonlinearElasticitySolver (Failed)
        198 - TestStokesFlowSolver (Failed)
        262 - TestNodeBasedCellPopulation (Failed)
        290 - TestOnLatticeSimulationWithPottsBasedCellPopulation (Failed)
        367 - TestMajorAirwaysCentreLinesCleaner (Subprocess aborted)
        382 - TestBidomainProblem (Failed)
        420 - TestMonodomainProblem (Failed)
        432 - TestPostProcessingWriter (Subprocess aborted)
```

**Comment by kwabenantim** [comment]
[Canonical releases Ubuntu 24.04 LTS Noble Numbat](https://canonical.com/blog/canonical-releases-ubuntu-24-04-noble-numbat)

**Comment by fcooper8472** [comment]
- [x] #263 
- [x] #264

It looks as though it MAY just be these two. As far as I can tell, the other tests that are failing are all to do with the VTK error (#249)

**Comment by fcooper8472** [comment]
There are still compiler warnings being emitted that relate to:

- [x] #197 #198 #231 

One specific issue relates to a weird interaction between `std::vector` and `ublas::c_vector` when the `c_vector` has dimension 1:

- [x] #280

**Comment by fcooper8472** [comment]
Just flagging that Python 3.12 (that comes out-of-the-box in 24.04) isn't yet supported by Chaste codegen:

https://github.com/ModellingWebLab/chaste-codegen/issues/281

**Comment by kwabenantim** [comment]
chaste-codgen now supports Python 3.12 in the latest release [0.10.5](https://pypi.org/project/chaste-codegen/0.10.5/). No changes need to be made in Chaste as it's already set up to pull the latest version in the 0.10.x series.

**Comment by fcooper8472** [comment]
We now fully support Ubuntu 24.04, and the website is updated to show it as the default.
