### ISSUE TITLE
Decommission old machines (Oxford CS machine rooms)

### ISSUE THREAD

**Issue by jmpf** [Chaste/Chaste#260]
See (and update!) https://github.com/Chaste/developer_wiki/wiki/Oxford-hardware:-current

Potential for removal
- [x] chaste.cs (old Trac server)
- [x] lofty.cs (Tower PC - IT support want to remove) [144M	/home/garmir/, 2.7G	/home/jonc/, 44M	/scratch/chaste/git_migration/git/projects/jmpf, 364K	/home/chaste/robinsonm/, 1.3G	/scratch/fcooper/]
- [x] muck.cs (Tower PC - IT support want to remove) [7.3G	/home/fcooper/, 33G	/home/chaste/home-files-restored/adaly,12G	/home/chaste/home-files-restored/fcooper, 28G	/home/chaste/home-files-restored/jonc, 12G	/home/chaste/home-files-restored/robinsonm, 56M	/home/chaste/home-files-restored/ross, 9.5G	/scratch/scratch/fcooper, 75G	/scratch/scratch/jonc, 50G	/scratch/scratch/robinsonm, 135G	/scratch/scratch/ross]
- [x] trix.cs (Tower PC - IT support want to remove) [ 365M	/home/garmir, 38M	/home/jonc, 6.8G	/home/ken, 24K	/home/chaste/jmpf/, 6.0G	/scratch/robinsonm/, 4.1M	/home/chaste/eclipse/workspace/fcooper/]
- [x] scoop.cs (Very old server for hosting two old Tesla GPU cards.  No-one's hassling us to remove it... yet)
- [x] appredict.cs (officially Dave's, @jmpf does not have access)

**Comment by mirams** [comment]
Happy to have my trix account deleted, nothing I need on there.

**Comment by jmpf** [comment]
> Happy to have my trix account deleted, nothing I need on there.

Ta.

**Comment by jmpf** [comment]
@mirams @fcooper8472 @adaly @jonc125 @martinjrobins 
Updated description to show where there may be files that can be recovered from the 3 target machines (lofty/muck/trix).  I haven't looked in detail but I think they're mainly chaste builds, infrastructure/software configuration attempts and (in one case) old photos.  I assume nothing needs to be recovered but I intend to retain the drives just in case.

**Comment by jonc125** [comment]
I took copies of everything I cared about when I left Oxford, so happy for my data to be deleted.

**Comment by martinjrobins** [comment]
same here, happy for everything to be deleted

**Comment by adaly** [comment]
Ditto!

**Comment by jmpf** [comment]
Thanks all for confirmations.  It's what I believed but I don't like throwing things away!

All three target machines are now de-registered from HFS backups.

**Comment by jmpf** [comment]
Is Scoop in use for anything?

Scoop has a self-host github runner on it.  From looking in /home/gh/actions-runner/_work/Chaste/Chaste/ I think that it was last triggered in February (so must have been superseded).

**Comment by jmpf** [comment]
Scoop unreachable (probably switched off permanently) from 21 June.

**Comment by jmpf** [comment]
> Scoop unreachable (probably switched off permanently) from 21 June.

Scoop decommissioned 27 June.  Tesla GPU cards and single hard drive have been recovered.

**Comment by jmpf** [comment]
appredict was decommissioned around 1 August. Hard drive has now been recovered.
