### ISSUE TITLE
Ubuntu 24.04 PETSC citation update

### ISSUE THREAD

**Issue by fcooper8472** [Chaste/Chaste#264]
The PETSc citation needs updating.

It's not clear to me how to find the appropriate citation, or where it should go, but it has been updated at least once since 3.15.

Perhaps @jmpf or @mirams could have a look?

**Comment by mirams** [comment]
This looks as if it was the last time we had to do this:
https://github.com/Chaste/Chaste/commit/562005227f9c7160dc45e00b76e8fadc4cec19e2.

I think Fergus Cooper is something of an expert though: https://github.com/Chaste/Chaste/commit/c24e79522672256bab230223911d7d0e8571a8a7

(probably the Chaste default citation wants updating too whilst we're at it!)

**Comment by fcooper8472** [comment]
Ha! Good find. I have no recollection of doing those.

I've just had a play around and I can't find where the updated citations are... but I imagine it's documented somewhere in PETSC.

**Comment by fcooper8472** [comment]
Closed by #276
