### ISSUE TITLE
Create user tutorial for cell-based simulation command line arguments and parameter sweeping

### ISSUE THREAD

**Issue by AlexFletcher** [Chaste/Chaste#267]
See https://github.com/Chaste/trac_archive/blob/6a7d720d0f6351f9b0d2c7b9b3464f4f265cfa41/attachment/ticket/2762/ExampleCellBasedExecutable.cpp, old tickets #2601 and #2762, and old wiki pages for inspiration; see also Boost program options and `CommandLineArguments`.

See also work done by @twinkarma as part of a previous BBSRC grant: https://github.com/twinkarma/chastesweep

**Comment by mirams** [comment]
Yeah, could probably be a generic tutorial (not just cell based) just showing how to use the `CommandLineArguments`. I think that basically does everything you need and boost program_options is a bit overkill, needing additional dependency etc.

**Comment by BJackal** [comment]
Created two tutorials for passing command line arguments to Chaste tests. First, simple hello world test which takes in command line arguements, adds inputs together and cout's the result. Second tutorial shows how to utilise bash script with command line arguments to create a vertex mesh with varying height and width based on inputs.

**Comment by mirams** [comment]
Could you stick a link to the branch in here @BJackal (see cog next to "Development" on the right hand toolbar)

**Comment by BJackal** [comment]
Two user tutorials have now been added for command line argument examples. The more simple "hello world" test case example and its corresponding bash script have been put in global. I'm not sure if this is the correct location but seemed the most appropriate. The second example of executing a simple vertex mesh test with a single command line argument for tissue height and width has also been added. The tutorial and its corresponding bash script have been placed within the cell_based section.

**Comment by Mintao919** [comment]
one of part comments (derived from the original TestRunningVertexBasedSimulationsTutorial.hpp) file shows the default time step 0.02 hours.  But I think it should be 0.002 hours if print results every 0.1 hours for 50 time steps. Which number is the correct one for defaul time step.  Furthermore, where can the default time step be found and modified ? How can it be changed ? Only in the orignal file or available to set it as an argument parameter ? Many thanks.   

        * For longer simulations, we may not want to output the results
         * every time step. In this case we can use the following method,
         * to print results every 50 time steps instead. As the default time step
         * used by the simulator (for vertex based simulations), is 0.02 hours, this method will cause the
         * simulator to print results every 6 minutes (i.e. 0.1 hours).
         */

**Comment by BJackal** [comment]
> one of part comments (derived from the original TestRunningVertexBasedSimulationsTutorial.hpp) file shows the default time step 0.02 hours. But I think it should be 0.002 hours if print results every 0.1 hours for 50 time steps. Which number is the correct one for defaul time step. Furthermore, where can the default time step be found and modified ? How can it be changed ? Only in the orignal file or available to set it as an argument parameter ? Many thanks.
> 
> ```
>     * For longer simulations, we may not want to output the results
>      * every time step. In this case we can use the following method,
>      * to print results every 50 time steps instead. As the default time step
>      * used by the simulator (for vertex based simulations), is 0.02 hours, this method will cause the
>      * simulator to print results every 6 minutes (i.e. 0.1 hours).
>      */
> ```

**EDIT: This comment is not accurate please see jmosborne's comment below but will leave the comment here as it still contains useful information.**

@Mintao919 , The default time step is defined in each class. For example within the Goldbeter1991SrnModel the default time step can be found on line 45 and is set at 0.1. For another method such as the DeltaNotchSrnModel on line 44 the default time step is set as 0.001.  

You should always be able to find if a method has a default time step in its corresponding .cpp file. However for good practice it would always be best to define your own time step in your simulation. You should not need to change the default time step itself as it can always be set and changed in your test directly using `simulator.SetDt(x);`

Looking through the tutorials should assist in the understanding of how simulations are ran. Two suggestions, TestRunningvertexBasedSimulationTutorial.hpp and TestOffLatticeSimulationWithVertexBasedCellPopulation.hpp

**Comment by jmosborne** [comment]
The cell based timestep is 1/120 for VT and OS and 1/200 for VD. If youre also solving odes (like Goldbeter) then it can uses a smaller timestep for the ODEs, but the simulator.SetDt(x) timestep is used for the cell movement.

**Comment by Mintao919** [comment]
> The cell based timestep is 1/120 for VT and OS and 1/200 for VD. If youre also solving odes (like Goldbeter) then it can uses a smaller timestep for the ODEs, but the simulator.SetDt(x) timestep is used for the cell movement.

Hey James, thanks for your comments. Could you please share the full names of VT, OS and VD. Many thanks. @jmosborne

**Comment by jmosborne** [comment]
Sorry, 
* VT-Voronoi Tesselation (MeshBased in Chaste) 
* OS-Overlapping Spheres (NodeBased in Chaste)
* VD-Vertex Dynamics (Vertex in Chaste)

**Comment by mirams** [comment]
Wants a manual entry adding to the tutorial menu page, probably under here: https://chaste.github.io/docs/user-tutorials/#core-functionality

**Comment by mirams** [comment]
Closed by https://github.com/Chaste/Chaste.github.io/pull/95
