### ISSUE TITLE
Mailing list incompatible with Google email

### ISSUE THREAD

**Issue by fcooper8472** [Chaste/Chaste#268]
The chaste-users@maillist.ox.ac.uk mailing list informed me that ~50% of users were bouncing.

This turned out to be because google (which handles not only gmail, but also e.g. @sheffield.ac.uk email) was blanket-rejecting all mail sent to the list.

The bounce messages contained the following:

```
    SMTP error from remote mail server after end of data:
    550-5.7.1 This message is not RFC 5322 compliant. There are multiple Reply-To
    550-5.7.1 headers. To reduce the amount of spam sent to Gmail, this message has
    550-5.7.1 been blocked. For more information, go to
    550-5.7.1  https://support.google.com/mail/?p=RfcMessageNonCompliant and review
    550 5.7.1 RFC 5322 specifications. j13-20020a5d618d000000b003498b74f4b7si8282258wru.286 - gsmtp
```

and was caused because the list had custom header field of `Reply-To: chaste-users@maillist.ox.ac.uk`, in addition to the list specifying reply-to as `sender`.

This caused every email to be non-compliant with RFC 5322.

I have rectified this by removing the custom header and setting reply-to as `all`.

**Comment by jmpf** [comment]
Fix: Black list most posters and send them a clear redirection to Discussions (a stronger warning about deprecation).

**Comment by ptheywood** [comment]
Last mailing list email 8th may, which bounced for some users (i.e. google). 

Would be nice to have, but not interested in spending time for this to be resolved.

**Comment by mirams** [comment]
What proportion are bouncing now?
