### ISSUE TITLE
Change default location of Chaste Test Output

### ISSUE THREAD

**Issue by fcooper8472** [Chaste/Chaste#270]
Related to #226 

In the linked PR, we discuss making the default location of the test output a subdirectory of the build dir. This will simplify some scenarios.

Currently, the default is `/tmp/$USER/testoutput` but, for instance, on Docker, you're not guaranteed to have a `$USER`.

**Comment by mirams** [comment]
Also note that the tutorial index page will want updating to mention this: https://chaste.github.io/docs/user-tutorials/

**Comment by mirams** [comment]
Will also be worth mentioning on a Latest News/Release Notes page.

**Comment by fcooper8472** [comment]
Docs updated, and PR merged.

Closing as complete.
