### ISSUE TITLE
Arrange September hackathon

### ISSUE THREAD

**Issue by AlexFletcher** [Chaste/Chaste#287]
Will this be in Oxford or Nottingham? Will it be on 17th September? What shall we do in it?

**Comment by kwabenantim** [comment]
It should be okay to have the Chaste hackathon on Tue 17 Sep in Nottingham. It will probably be freshers' welcome week as well so might need to book a room early.

**Comment by mirams** [comment]
Happy to do it in Nottingham, let's book that day in.

**Comment by ptheywood** [comment]
Possible topics for during hackathon:

+ PyChaste
  + This would be a good topic for longer workshops, broader / different group of people than for a c++ workshop.
    + I.e. demonstrate can do a range of things from a jupyter notebook
+ OpenVT / PerMedCOE
  + Are there changes which can be made to strengthen the appeal/offer of Chaste (PDE etc). 
  + Consider formally inviting non-chaste developers to discuss these topics.
    + Fergus to enquire about this on the oxfrod chaste mailing list & directly to relevant people
+ Website
  + Misc tidying / finishing off
  + But this could be done offline at any time, so focussing on discussions instead
+ GPU
  + Higher level discusion about where this gets taken next, should be in a better place wiht a cell absed example by then for concrete info
+ [Electrode question](https://github.com/Chaste/Chaste/discussions/141) on discussion mailing list (@mirams  & @jmpf)
+ SBML
  + Define how this is wanted
  + Possibly good to get input from OpenVT
+ Morpheus

**Comment by MILeach** [comment]
Could also discuss:
 - Capsules - potential attendee at hackathon has been doing some work on this
 - Next workshop  
   - Very early thoughts of pychaste focus - attract people who are not interested in C++

**Comment by ptheywood** [comment]
@fcooper8472 Could you ask (some of) WCMB if they would like to attend this?

**Comment by MILeach** [comment]
In additition we could have a think/chat about:
- what we want the improved website to look like
- integration & use of pychaste bindings once they are merged into the trunk
