### ISSUE TITLE
Proper redirect page for Chaste downloads

### ISSUE THREAD

**Issue by jmpf** [Chaste/Chaste#289]
The Chaste download link that we put in papers <http://www.cs.ox.ac.uk/chaste/download.html> looks for half a second as if you'll be able to click what you want (i.e. old project *.tar.gz files associated with user projects for papers) but now seems to forward to <https://chaste.github.io/docs/#getting-the-code> which doesn't have anything about getting what you might want. We should probably put some link there to make them accessible again

(in general, it is a bit odd that these forwards aren't happening before the old page is rendered in the browser??)

[Slack Message](https://chasteteam.slack.com/archives/C4GLVGALS/p1719909155337009)

**Comment by jmpf** [comment]
The pages which were hosted on www.cs.ox.ac.uk all now redirect with 
```<meta http-equiv="refresh" content="0; url=https://chaste.github.io/docs/#getting-the-code" />``` 
or similar.  I think this ought to be instantaneous but, because the content of the old page is there, it probably loads something before redirecting.  The redirections from the old server chaste.cs.ox.ac.uk are done using Apache rewrite rules but we can't do that here because we don't run the website.

- [x] Make the redirections happen tidily/faster
- [x] Put some really obvious instructions on https://chaste.github.io/docs/#getting-the-code

**Comment by fcooper8472** [comment]
can we ask CS IT to do the redirection at the server level for us?

**Comment by jmpf** [comment]
> can we ask CS IT to do the redirection at the server level for us?

I can ask.  In the first instance I will get rid of the old page contents so that loading and redirecting don't interfere.  Either way the first to-do is with me.  @mirams should probably edit the "getting the code" text.

**Comment by mirams** [comment]
to say what.... where are the old downloads again?

**Comment by fcooper8472** [comment]
Ah, they might have never made it to a public location. Leave that with me, and I'll put a link below here when they're ready.

**Comment by jmpf** [comment]
Removing the <body> of the message makes it so that you see a blank page for half a second.  I don't think that the redirection is a whole lot faster.  It will do for now but I intend to put in proper 301 redirects when I get the right permissions.

**Comment by jmpf** [comment]
Okay.  I have done local 301 redirects so that the old file contents are no longer read.

```
linux[/auto/fs/website/projects/chaste]$ cat  .htaccess
# Redirections now that these pages are no longer maintained
RedirectMatch 301 about.html            https://chaste.github.io/
RedirectMatch 301 cardiac_index.html    https://chaste.github.io/components/cardiac
RedirectMatch 301 cell_based_index.html https://chaste.github.io/components/cell-based
RedirectMatch 301 documentation.html    https://chaste.github.io/docs
RedirectMatch 301 download.html         https://chaste.github.io/docs/#getting-the-code
RedirectMatch 301 functionality.html    https://chaste.github.io/components
RedirectMatch 301 index.html            https://chaste.github.io/
RedirectMatch 301 lung_index.html       https://chaste.github.io/components/lung
RedirectMatch 301 methodology.html      https://chaste.github.io/
RedirectMatch 301 news.html             https://chaste.github.io/
RedirectMatch 301 publications.html     https://chaste.github.io/publications
RedirectMatch 301 theteam.html          https://chaste.github.io/team
RedirectMatch 301 workshop.html         https://chaste.github.io/workshops

# Hide automatic infrastructure for building website from Subversion (no longer used)
<Files make.py>
Deny from all
</Files>

<Files template.html>
Deny from all
</Files>
```

**Comment by jmpf** [comment]
> to say what.... where are the old downloads again?

See https://github.com/Chaste/Chaste/issues/133#issuecomment-2077015862 and any other discussion on that issue

**Comment by fcooper8472** [comment]
I've spent some time trying to find an alternative home for the Chaste data that doesn't rely on it sitting on an Oxford server.

There is 9.0Gb of data, and the data files over 100Mb are:

```
3.4G    ./downloads/data/related/OxfordRabbitMRData.tar.gz
847M    ./downloads/data/compat/OxfordRabbitHeartWithBath_binary_3.2.tgz
600M    ./downloads/data/compat/OxfordRabbitHeart_binary_3.2.tgz
477M    ./downloads/data/compat/OxfordRabbitHeartWithBath_binary.tgz
477M    ./downloads/data/compat/OxfordRabbitHeartWithBath_binary_3.1.tgz
374M    ./downloads/data/compat/OxfordRabbitHeart_binary.tgz
374M    ./downloads/data/compat/OxfordRabbitHeart_binary_3.1.tgz
208M    ./downloads/projects/MouseLesion_release_3_3.tgz
167M    ./downloads/projects/CellProliferation09_project_release_1.tgz
153M    ./downloads/projects/Frontiers2014_release_3_3.tgz
119M    ./downloads/previous/chaste_release_3_1.tgz
118M    ./downloads/previous/chaste_release_2_2.tgz
117M    ./downloads/previous/chaste_release_3_4.tgz
116M    ./downloads/previous/chaste_release_3_0.tgz
107M    ./downloads/previous/chaste_release_3_3.tgz
107M    ./downloads/previous/chaste_release_3_2.tgz
```

If the sizes were smaller, we could just commit these files to a repository and link directly to them from the new website.
I had thought we could use the git large file storage (https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage). We seem to be able to add extra units of LFS data for free, so I tried that and added a test file: it worked fine, but, you never end up with a direct link to the data for download, so unfortunately it's not a viable solution.

Zenodo might be a good place to keep these files?

We could have one record for each of:

```
data/ 
previous/
projects/
related/
```

**Comment by mirams** [comment]
For 'previous' probably can ditch those and just point at the relevant tags:
 * https://github.com/Chaste/Chaste/tags?after=release_2017.1 for 3.1 to present
 * https://github.com/Chaste/Old-Chaste-svn-mirror/tags for 3.1 and earlier

**Comment by ptheywood** [comment]
Example zenodo repo https://zenodo.org/records/10596993 with multiple datasets

**Comment by jmpf** [comment]
Note that https://chaste.cs.ox.ac.uk/old-chaste-data/downloads/data/compat/index.txt contains the attribution for these data sets: 
```4 million node rabbit ventricular tetrahedral mesh (in this case without perfusing bath) reconstructed from MRI data, in a binary format <b>suitable for Chaste 3.1 and below</b>.  See Bishop et al. "Development of an anatomically detailed MRI-derived rabbit ventricular model..." (Am J Physiol Heart Circ Physiol, 2010).```
