### ISSUE TITLE
build configure imcomplete

### ISSUE THREAD

**Issue by halim-k** [Chaste/Chaste#29]
I'm not familiar to using cmake, and while following the user guide for installation,
I met this configuring error down below., Is there any way to solve this issue,? 

```
CMake Error at cmake/Modules/ChasteMacros.cmake:90 (add_custom_command):
  add_custom_command Wrong syntax.  A TARGET or OUTPUT must be specified.
Call Stack (most recent call first):
  cmake/Modules/ChasteMacros.cmake:301 (chaste_do_cellml)
  cmake/Modules/ChasteMacros.cmake:401 (Chaste_DO_COMMON)
  heart/CMakeLists.txt:56 (chaste_do_component)
```

OS: Ubuntu 18.04.5 LTS

**Comment by fcooper8472** [comment]
Hi @halim-k, please could you provide some more information?

- which version of CMake you're using
- what command you are running that generates this error
- what directory (relative to Chaste) are you running CMake from

**Comment by halim-k** [comment]
I thought I used the latest version of the CMake, but I guess the CMake version might be causing the problem. 
Recently, I have not been meeting the issue again for a long time.  
Thank you so much.

> Hi @halim-k, please could you provide some more information?
> 
>     * which version of CMake you're using
> 
>     * what command you are running that generates this error
> 
>     * what directory (relative to Chaste) are you running CMake from
