### ISSUE TITLE
Changes to vtkGeometryFilter in vtk 9

### ISSUE THREAD

**Issue by fcooper8472** [Chaste/Chaste#298]
Related to #292 

A test failure previously thought to be related to #249 in fact relates to modifications to vtkGeometryFilter in VTK itself, sometime between v9.1 and v9.3. The affected Chaste source is:

https://github.com/Chaste/Chaste/blob/60e837ec54cfdf0e6b6cce5c8a3e037d883c9a61/mesh/src/reader/VtkMeshReader.cpp#L388

with associated test:

https://github.com/Chaste/Chaste/blob/60e837ec54cfdf0e6b6cce5c8a3e037d883c9a61/mesh/test/reader/TestVtkMeshReader.hpp#L208

The `vtkGeometryFilter` extracts boundary geometry from a dataset, and the test above assumed that faces are provided in a deterministic order. In v9.1 (and all earlier versions for at least 10 years) the order was:

```
94: Entering TestGetNextFaceData
94: DEBUG: ed.NodeIndices = {11,3,0}
94: DEBUG: ed.NodeIndices = {3,8,0}
94: DEBUG: ed.NodeIndices = {5,10,11}
94: DEBUG: ed.NodeIndices = {10,5,6}
94: DEBUG: ed.NodeIndices = {5,9,6}
94: DEBUG: ed.NodeIndices = {4,8,5}
94: DEBUG: ed.NodeIndices = {11,4,5}
94: DEBUG: ed.NodeIndices = {8,4,0}
94: DEBUG: ed.NodeIndices = {4,11,0}
94: DEBUG: ed.NodeIndices = {3,10,2}
94: DEBUG: ed.NodeIndices = {9,3,2}
94: DEBUG: ed.NodeIndices = {9,2,6}
94: DEBUG: ed.NodeIndices = {2,10,6}
94: DEBUG: ed.NodeIndices = {3,11,7}
94: DEBUG: ed.NodeIndices = {11,10,7}
94: DEBUG: ed.NodeIndices = {10,3,7}
94: DEBUG: ed.NodeIndices = {8,3,9}
94: DEBUG: ed.NodeIndices = {1,8,9}
94: DEBUG: ed.NodeIndices = {5,1,9}
94: DEBUG: ed.NodeIndices = {1,5,8}
94: Passed
```

whereas in v9.3, the order is changed:

```
94: Entering TestGetNextFaceData
94: DEBUG: ed.NodeIndices = {0,4,11}
94: DEBUG: ed.NodeIndices = {0,8,4}
94: DEBUG: ed.NodeIndices = {0,3,8}
94: DEBUG: ed.NodeIndices = {0,11,3}
94: DEBUG: ed.NodeIndices = {1,5,8}
94: DEBUG: ed.NodeIndices = {1,9,5}
94: DEBUG: ed.NodeIndices = {1,8,9}
94: DEBUG: ed.NodeIndices = {2,9,3}
94: DEBUG: ed.NodeIndices = {2,3,10}
94: DEBUG: ed.NodeIndices = {2,10,6}
94: DEBUG: ed.NodeIndices = {2,6,9}
94: DEBUG: ed.NodeIndices = {3,9,8}
94: DEBUG: ed.NodeIndices = {3,7,10}
94: DEBUG: ed.NodeIndices = {3,11,7}
94: DEBUG: ed.NodeIndices = {4,5,11}
94: DEBUG: ed.NodeIndices = {4,8,5}
94: DEBUG: ed.NodeIndices = {5,9,6}
94: DEBUG: ed.NodeIndices = {5,6,10}
94: DEBUG: ed.NodeIndices = {5,10,11}
94: DEBUG: ed.NodeIndices = {7,11,10}
94: Passed
```

As far as I can tell, there is no canonical ordering, as the faces (`VTK_TRIANGLE`s) are calculated from the geometric data. Numerous performance enhancements specifically related to `vtkGeometryFilter` were introduced in [v9.2](https://docs.vtk.org/en/latest/release_details/9.2.html) and [v9.3](https://docs.vtk.org/en/latest/release_details/9.3.html) that could explain this behaviour.

Furthermore, for each face, the indices are only unique up to a rotation.

It ought to be sufficient to check that each returned face is indeed valid, rather than checking that they are returned in a specific order.

**Comment by fcooper8472** [comment]
Closed by #299

**Comment by fcooper8472** [comment]
This was closed when I merged into a feature branch; reopening, and will close when merged into develop.

**Comment by mirams** [comment]
I think this just made it into develop
