### ISSUE TITLE
PETSc 3.19 vector assembly

### ISSUE THREAD

**Issue by fcooper8472** [Chaste/Chaste#302]
While working on Ubuntu 24.04 support (#257), the following was misidentified as being related to #249 but is a separate PETSc-related problem.

v3.19 introduced a change (https://petsc.org/release/changes/319/):

> Enforce the rule that VecAssemblyBegin() and VecAssemblyEnd() must be called on even sequential vectors after calls to VecSetValues().

This was leading to test failures:

```
The following tests FAILED:
	191 - TestCompressibleNonlinearElasticitySolver (Failed)
	199 - TestStokesFlowSolver (Failed)
```

The Chaste function `PetscVecTools::Finalise` is responsible for applying these two methods:
https://github.com/Chaste/Chaste/blob/60e837ec54cfdf0e6b6cce5c8a3e037d883c9a61/linalg/src/PetscVecTools.cpp#L48-L52

But as things stand there are several instances of unfinalized calls to `VecSetValues` in `PetscVecTools`.

Adding a call to `Finalise` after each of these calls resolves the test failures, but it's possible that this would introduce regressions if there were ever many calls to `PetscVecTools::AddToElement` in a tight loop.

Perhaps @mirams and @jmpf could look at the associated PR and comment if we need a different approach.

**Comment by mirams** [comment]
Hmmm, it seems the Chaste way is for the finalise to be called once after the assembling (altering) of matrices and vectors is all finished. i.e. a public method `PetscVecTools::Finalise` exists which the users of other `PetscVecTools::OtherMethods()` should probably also call. So something should be taking responsibility for calling finalise 

From looking at some bits of code that tends to be what is done. I think it can be done more than once (you finalise, mess about, finalise again), see e.g. https://github.com/Chaste/Chaste/blob/60e837ec54cfdf0e6b6cce5c8a3e037d883c9a61/continuum_mechanics/src/solver/StokesFlowSolver.hpp#L298 and the following call below it. So it might be harmless but wasteful to introduce extra calls, I'm not sure. But I think my preferred thing would instead be to make the code calling the methods that are altered in the pull request call `PetscVecTools::Finalise()` as well. See what @jmpf thinks though!

**Comment by mirams** [comment]
We should probably be symmetric in the approach for PetscVecTools and PetscMatTools anyway, even if PETSc aren't quite yet they probably will apply this change to matrices as well soon I guess.

**Comment by jmpf** [comment]
c11b00db3 will fix remaining failing tests - subject to PR #303

**Comment by jmpf** [comment]
> Hmmm, it seems the Chaste way is for the finalise to be called once after the assembling (altering) of matrices and vectors is all finished.

Pedantic point: it's the PETSc way rather than the Chaste way.

>  See what @jmpf thinks though!

I haven't approved #303 as it seems like an inefficient abuse of the PETSc infrastructure.

**Comment by jmpf** [comment]
Pretty sure that c11b00d works and thus PR #303 should be deleted.
