### ISSUE TITLE
#3013 - Fix coverage

### ISSUE THREAD

**Issue by kwabenantim** [Chaste/Chaste#32]
This issue continues the discussion for legacy trac ticket 3013:
___

[jmpf](https://github.com/orgs/Chaste/people/jmpf) created the following ticket on 2022-07-27 at 09:35:17, it is owned by [jmpf](https://github.com/orgs/Chaste/people/jmpf)

There are two issues with coverage on buildbot@scoop

An upgrade from 16.04 to 20.04 caused the coverage tests to report some false negatives. These are mostly default: in switch statements: https://chaste.cs.ox.ac.uk/buildbot/Nightly%20Coverage/coverage1734/global/src/FileFinder.cpp.gcov.html
An recent upgrade to the PETSc version has caused the buildbot to stop being able to build (trac ticket 3075).
___

Comment by [jmpf](https://github.com/orgs/Chaste/people/jmpf) on 2022-07-27 at 09:45:26

16.04 had lcov 1.12-2
18.04 has lcov 1.13-3
20.04 has lcov 1.14-2
22.04 has lcov 1.15-1
Comment by [jmpf](https://github.com/orgs/Chaste/people/jmpf) on 2022-07-27 at 10:07:48

During the upgrade and reconfiguration from PETSc 3.6.2 to PETSc 3.12.5 I made a build that is ready to use with lcov: https://chaste.cs.ox.ac.uk/trac/ticket/3075#comment:7 I guess that the old stale CMake files are interfering. Deleted configuration and retesting.
___

Comment by [jmpf](https://github.com/orgs/Chaste/people/jmpf) on 2022-07-27 at 12:54:41

Replying to jmpf@…:

Deleted configuration and retesting.
That worked for nightly coverage and for nightly memory testing too.

Comment by [jmpf](https://github.com/orgs/Chaste/people/jmpf) on 2022-07-28 at 14:31:04

Way to build coverage on Scoop

```
mkdir Debug_develop
export PETSC_ARCH=linux-gnu
export PETSC_DIR=/home/bob/petsc-3.12.5
export LD_LIBRARY_PATH=/home/bob/petsc-3.12.5/linux-gnu/lib
cmake -DCMAKE_BUILD_TYPE=Debug -DChaste_UPDATE_PROVENANCE=OFF -DChaste_COVERAGE_CPUS=11 ..
make -j12 Continuous Parallel
make -j6 coverage
# To repeat parts of post-processing from "make coverage"
usr/bin/lcov --config-file /home/jmpf/eclipse/workspace/Chaste/cmake/Config/lcovrc --directory . --capture --output-file coverage.info
/usr/bin/lcov --config-file /home/jmpf/eclipse/workspace/Chaste/cmake/Config/lcovrc --remove coverage.info "/home/bob/petsc*" "/usr/*" "*/fortests/*" "*/test/*" "*/3rdparty/*" "*/global/src/random/*" "Debug/*" "*/Debug_*/*" "cxxtest/*" --output-file coverage.info.cleaned set "(" _page_title "\"Chaste Coverage Results for commit \"" ")"
/usr/bin/genhtml --title "" --config-file /home/jmpf/eclipse/workspace/Chaste/cmake/Config/lcovrc --no-function-coverage -o coverage coverage.info.cleaned
#DON'T DO:	/usr/bin/cmake -E remove coverage.info coverage.info.cleaned
/usr/bin/python3 /home/jmpf/eclipse/workspace/Chaste/cmake/process_coverage_output.py coverage
```
___

Comment by [jmpf](https://github.com/orgs/Chaste/people/jmpf) on 2022-07-28 at 14:34:22

The first issue with failing coverage from files which have been auto-generated. See top 3 lines of https://chaste.cs.ox.ac.uk/buildbot/Nightly%20Coverage/coverage1740/

This is caused by an incorrect wildcard/glob pattern and should be fixed by changing Debug_*/* to */Debug_*/* on line 844 of CMakeLists.txt.
___

Comment by [jmpf](https://github.com/orgs/Chaste/people/jmpf) on 2022-10-26 at 09:15:28

Note that existing work on this ticket is available:

```
git checkout ticket_3103
```
___

Comment by [mirams](https://github.com/orgs/Chaste/people/mirams) on 2022-10-26 at 10:14:08

For those not so familiar with LCOV and how we have it set up see (track ticket 2858) for previous work and how to mark files, lines or blocks as purposely excluded etc.

**Comment by fcooper8472** [comment]
[This case]()https://chaste.cs.ox.ac.uk/buildbot/Nightly%20Coverage/coverage1869/crypt/src/cell/cycle/SimpleWntCellCycleModel.cpp.gcov.html) is:
```
     186                 :          0 :         case UNSIGNED_UNSET:
     187                 :            :         {
     188                 :            :             // If you trip this you have tried to use a simulation without setting the dimension.
     189                 :            :             NEVER_REACHED;
     190                 :            :         }
     191                 :          0 :         default:
     192                 :            :             NEVER_REACHED;
```

illustrates two issues: every `default` containing a `NEVER_REACHED` is being reported as uncovered, but also other switch cases are too.

We might need to ignore all `default:` lines, and put some specific exclusions in the source comments for other cases.

**Comment by mirams** [comment]
List of troublesome things 
```
default:
    NEVER_REACHED;
```
default line lighting up is the majority of them.

Here a line split over two lines, which for some reason confuses it (templates?):
https://chaste.cs.ox.ac.uk/buildbot/Nightly%20Coverage/coverage1869/heart/src/tissue/AbstractCardiacTissue.cpp.gcov.html
```
0 :     AbstractPurkinjeCellFactory<ELEMENT_DIM,SPACE_DIM>* p_purkinje_cell_factory
593 :        = dynamic_cast<AbstractPurkinjeCellFactory<ELEMENT_DIM,SPACE_DIM>*>(pCellFactory);
```

Strange one, that looks like gcov is doing something wrong.
https://chaste.cs.ox.ac.uk/buildbot/Nightly%20Coverage/coverage1869/mesh/src/common/AbstractMesh.cpp.gcov.html
```
0 :         case 1:
81 :             displacement[0] = xMovement;
```

Ditto in https://chaste.cs.ox.ac.uk/buildbot/Nightly%20Coverage/coverage1869/cell_based/src/mesh/PottsMesh.hpp.gcov.html
```
 0 : do
   : {
27 :    ++mElementIter;
   : }
27 : while (!IsAtEnd() && !IsAllowedElement());
```

Another strange one:
https://chaste.cs.ox.ac.uk/buildbot/Nightly%20Coverage/coverage1869/heart/src/stimulus/tissue_electrodes/ElectrodesStimulusFactory.cpp.gcov.html
```
0 :     boost::shared_ptr<RegularStimulus> p_stimulus;
...<a loop and stuff>
1054 :     return p_stimulus;
```

potentially a real one to fix?
https://chaste.cs.ox.ac.uk/buildbot/Nightly%20Coverage/coverage1869/cell_based/src/population/PottsBasedCellPopulation.cpp.gcov.html

**Comment by fcooper8472** [comment]
Coverage reporting has now been moved to Codecov: https://app.codecov.io/github/Chaste/Chaste/

There is a new file [.codecov.yml](https://github.com/Chaste/Chaste/blob/c1f0aa408acb6dd3a227693947d060b4a5096cf4/.codecov.yml) that contains codecov configuration.

In the following comments I will address specific coverage failures and how I propose to address them.

**Comment by fcooper8472** [comment]
Some lines containing just a `}` are marked uncovered.

I have added the following regex: `^\s*}\s*$` to `lcov_excl_line`.

in [this commit](https://github.com/Chaste/Chaste/commit/409479d48549e652d37a1381b691daee18626aba).

@jmpf does this seem appropriate?

**Comment by fcooper8472** [comment]
Some examples of:

```
default:
    NEVER_REACHED;
```
or
```
default:
{
    NEVER_REACHED;
}
```
have the line `default:` reported as uncovered.

I propose adding `^\s*default:\s*$` to `lcov_excl_line`. I think this is safe because every instance of `default:` that does not also contain braces on the same line must have at least one statement underneath that will have coverage tested.

@jmpf does that sound OK?

In addition, some lines like:
```
default :
```
were uncovered, due to the whitespace before `:` which caused the above regex to not match: but these have been fixed by removing the whitespace in line with our coding conventions.

**Comment by fcooper8472** [comment]
There are examples like this:

```
      52                 :        213 : Cylindrical2dVertexMesh::Cylindrical2dVertexMesh(Cylindrical2dMesh& rMesh, bool isBounded)
      53                 :          0 :     : mWidth(rMesh.GetWidth(0)),
      54                 :        213 :       mpMeshForVtk(nullptr)
      55                 :            : {
```

```
      54                 :         69 : Toroidal2dVertexMesh::Toroidal2dVertexMesh(Toroidal2dMesh& rMesh, bool isBounded)
      55                 :          0 :     : mWidth(rMesh.GetWidth(0)),
      56                 :         69 :       mHeight(rMesh.GetWidth(1)),
      57                 :         69 :       mpMeshForVtk(nullptr)
      58                 :            : {
```

where the first class member initialisation (on the line containing the `:`) is reported as uncovered.

I propose adding `^\s*:\s+` to `lcov_excl_line` as having performed a search in the codebase, nothing other than class member initialisations contains this pattern and I believe it should be perfectly safe to ignore all such lines.

@jmpf any thoughts on this?

**Comment by fcooper8472** [comment]
In addition, there are several instances of `case` statements being listed as uncovered:

[AbstractMesh](https://app.codecov.io/github/Chaste/Chaste/commit/841b706650fc228261d2e09f3119e44f7ec79c6f/blob/mesh/src/common/AbstractMesh.cpp#L360)
```
  switch (SPACE_DIM)
  {
      case 3:
          displacement[2] = zMovement;
      // fallthrough on purpose
      case 2:
          displacement[1] = yMovement;
      // fallthrough on purpose
      case 1:
          displacement[0] = xMovement;
          // fallthrough on purpose
  }
```
The fallthrough here is deliberate, and while the `case 1` may indeed never be hit, the code here is definitely tested, so I will add an `LCOV_EXCL_LINE`.

[StreeterFibreGenerator](https://app.codecov.io/github/Chaste/Chaste/commit/841b706650fc228261d2e09f3119e44f7ec79c6f/blob/heart/src/problem/StreeterFibreGenerator.cpp)
```
            case HeartGeometryInformation<SPACE_DIM>::UNKNOWN:
            default:
                NEVER_REACHED;
```
Both of these are `NEVER_REACHED` and I will add `LCOV_EXCL_LINE`.

Similarly, several other instances will be ignored after evaluation.

**Comment by fcooper8472** [comment]
The only substantial chunk of uncovered code is now due to the sytem PETSc not coming with ParMetis support, which prevents the method `PetscMatrixPartitioning` from being run.

We will need to try to make a non-system PETSc available for the coverage builder.

**Comment by fcooper8472** [comment]
Just a note that, for full coverage, it looks as though we need PETSc with:

- ParMetis
- Hypre

@kwabenantim relevant for when we discuss this next week.

**Comment by fcooper8472** [comment]
See eebbb5366ef07a1c4dcdd590ce2e1d2abc8ff104 for fix in destructor of `PottsBasedCellPopulation`.

**Comment by kwabenantim** [comment]
> Just a note that, for full coverage, it looks as though we need PETSc with:
> 
> * ParMetis
> * Hypre
> 
> @kwabenantim relevant for when we discuss this next week.

The [chaste/runner](https://hub.docker.com/r/chaste/runner) docker image builds PETSc with support for both ParMetis and Hypre ([install_petsc_hdf5.sh#L189](https://github.com/Chaste/dependency-modules/blob/main/scripts/install_petsc_hdf5.sh#L189)) so will probably be one option.

**Comment by jmpf** [comment]
All done and green.
