### ISSUE TITLE
Release Chaste 2024.2

### ISSUE THREAD

**Issue by fcooper8472** [Chaste/Chaste#332]
This will be the first release to support Ubuntu 24.04 LTS

**Comment by bdevans** [comment]
Building release `2024.2` on `noble` for `arm64` CPUs is still broken :(
```
The following packages have unmet dependencies:
 chaste-dependencies : Depends: libvtk9-dev (= 9.3.0+dfsg1-1build1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
To reproduce, clone `chaste-docker`, switch to the `noble` branch and run `MULTI_ARCH_BUILD=false make release` on `arm64` hardware.

**Comment by mirams** [comment]
Getting this working on docker and new macs seems a priority, so keeping this in play in the BBR board unless there's a new issue for dealing with it.

**Comment by fcooper8472** [comment]
I'm going to close this issue again, and move discussion of this issue to #338 

Note that this is also the same issue as #314 and it's related to the chaste-dependencies package providing a patched VTK that isn't arm64-compatible, rather than being related to the latest release.
