### ISSUE TITLE
Should the name spaces of XSDs be updated?

### ISSUE THREAD

**Issue by jmpf** [Chaste/Chaste#334]
[ChasteParameters_2017_1.xsd](https://github.com/Chaste/Chaste/blob/develop/heart/src/io/ChasteParameters_2017_1.xsd) and older files contain schemas that look like this:
`<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://chaste.comlab.ox.ac.uk/nss/parameters/2017_1"
  xmlns="https://chaste.comlab.ox.ac.uk/nss/parameters/2017_1" elementFormDefault="qualified">`

`chaste.comlab.ox.ac.uk` has been dead a long time.  For a schema is it important to have a live url or is it more important to have a url that doesn't change?

**Comment by mirams** [comment]
@jonc125 I think prefers that they don't change. I'm pretty sure we've had ones that have never pointed to anything, although it would be friendlier to have a landing page that points to some documentation!

**Comment by jonc125** [comment]
It doesn't matter if the URI doesn't resolve to anything - it's purely a unique identifier. But if you change it in the schema, then no older parameters files with the original URI will load...

**Comment by jmpf** [comment]
Thanks for the input.  That's what I believed to be true.  Trouble is that the schema has been static for so long now that we only review it on release days.  I will comment the release instructions and/or schema so future me is reassured.
