### ISSUE TITLE
Amend template user project to avoid potential problems with TestHello in the presence of multiple user projects

### ISSUE THREAD

**Issue by kwabenantim** [Chaste/Chaste#34]
This issue continues the discussion for legacy trac ticket 3098:
___

[AlexFletcher](https://github.com/orgs/Chaste/people/AlexFletcher) created the following ticket on 2022-04-28 at 08:47:02, it is owned by [AlexFletcher](https://github.com/orgs/Chaste/people/AlexFletcher)

Modify setup_project.py to rename TestHello to something like TestHello_[MyProjectName], just to reduce the chance of this happening in future? (Though if someone just copies the template user project directly and doesn't run setup_project.py then this wouldn't help them.)

See also (trac ticket 2857). https://github.com/Chaste/trac_archive/blob/master/issues/2857.md

**Comment by bdevans** [comment]
FYI, I've started including the GitHub command line tools in the docker image so that the `template_project` can be cloned as a template (`gh repo create ${REPO} --public --clone --template https://github.com/Chaste/template_project.git`).

**Comment by AlexFletcher** [comment]
This has been done.
