### ISSUE TITLE
Finish migration to GitHub

### ISSUE THREAD

**Issue by kwabenantim** [Chaste/Chaste#35]
This issue continues the discussion for legacy trac ticket 3081:
___

[fcooper8472](https://github.com/orgs/Chaste/people/fcooper8472) created the following ticket on 2021-12-01 at 17:49:37, it is owned by [fcooper8472](https://github.com/orgs/Chaste/people/fcooper8472)

Joe and I have recently migrated our primary git repo to GitHub.

All branches are now available here: https://github.com/Chaste/Chaste

Items left to do:

- Find all references to existing repo and remove them
___

Comment by [AlexFletcher](https://github.com/orgs/Chaste/people/AlexFletcher) on 2022-04-28 at 08:49:46

Does this ticket include tasks associated with moving from trac tickets to e.g. github projects? If so, then an outstanding task is to investigate how to create a github project associated with the BBR grant, and implement this; otherwise, we should create a new ticket for this task.
___

Comment by [fcooper8472](https://github.com/orgs/Chaste/people/fcooper8472) on 2022-05-20 at 11:04:09

We want to:

- migrate tickets to GitHub issues
- move bits of wiki that are private & useful to a wiki associated with a private repo (Chaste admin etc)
- public & useful pages can be added to the chaste GitHub pages website (to include auto-generated tutorials, Doxygen etc)

**Comment by kwabenantim** [comment]
Update: @MauriceHendrix, @fcooper8472, @MILeach and I have migrated the old trac tickets into a GitHub repo.

**Comment by fcooper8472** [comment]
Along with #50 this is superseded by #38 which has now become the single umbrella issue to keep track of remaining tasks relating to migrating various infrastructure to GitHub.
