### ISSUE TITLE
#3060 - PETSc 3.15 support

### ISSUE THREAD

**Issue by kwabenantim** [Chaste/Chaste#37]
This issue continues the discussion for legacy trac ticket 3060:
___

[mirams](https://github.com/orgs/Chaste/people/mirams) created the following ticket on 2021-04-06 at 10:13:32, it is owned by [mirams](https://github.com/orgs/Chaste/people/mirams)

Released recently: https://www.mcs.anl.gov/research/projects/petsc/documentation/changes/315.html

There could be some changes that need addressing.

Todo:

* Get build working
* Add to testing rotation
* Update InstallGuides/DependencyVersions

---
Comment by [jmpf](https://github.com/orgs/Chaste/people/jmpf) on 2022-06-17 at 11:44:58

Ubuntu 22.04 LTS uses this version of PETSc.  There are some failures on 22.04, notably KSP exceptions in the tests in `TestCardiacElectroMechanicsTutorial`.  It's likely that they are caused by the change of PETSc, but should be investigated further.

---
Comment by [jmpf](https://github.com/orgs/Chaste/people/jmpf) on 2022-07-06 at 14:41:49

I think I've got a working version of Chaste with PETSc 3.15 now:

```

6: 	<Libraries>
6: 		<CompiledIn>
6: 			<PETSc>3.15.5</PETSc>
6: 			<Boost>1.71.0</Boost>
6: 			<HDF5>1.12.0</HDF5>
6: 			<Parmetis>4.0.3</Parmetis>
6: 		</CompiledIn>

```

The fact that it's pulled in HDF5 at 1.12 is a headache because there's interface changes there.

Unfortunately I haven't yet managed to replicate the error in `TestCardiacElectroMechanicsTutorial`.  That is, it passes this test suite.  Further investigation needed.

---
Comment by [mirams](https://github.com/orgs/Chaste/people/mirams) on 2022-07-06 at 15:08:21

([trac ticket 3063] is the ticket for HDF5 1.12, no work on it yet!)

**Comment by kwabenantim** [comment]
#48 
#86

**Comment by fcooper8472** [comment]
Closing as fixed.
