### ISSUE TITLE
[JOSS REVIEW] Update commands in paper to work with docker

### ISSUE THREAD

**Issue by finsberg** [Chaste/Chaste#4]
I am trying to run the demos written in the joss paper using the pre-built docker image and the command
```
docker run -it --init --rm -v chaste_data:/home/chaste chaste/chaste-docker:2019.1
```
Inside this container, the environment variable `CHASTE_SRC` is called `CHASTE_SRC_DIR` instead, and the output directory is called `testoutput` instead of `test_summary` as you write in the paper. 

It would be good if you could tag one docker image that had the exact same folder structure and environment variables as you describe in the paper. 

By the way, everything seems to run fine using the correct folders.

**Comment by fcooper8472** [comment]
Hi @finsberg, thanks for spotting those inconsistencies.

For `CHASTE_SRC`, I have updated the JOSS paper to rename that to `CHASTE_SOURCE_DIR` for consistency with the docker image.

As far as the location of the test output is concerned, I have added instructions to the JOSS paper to ensure that `$CHASTE_TEST_OUTPUT` is set to a valid directory.  In the docker image, this is set up automatically.  You should now see test output in, for instance, `$CHASTE_TEST_OUTPUT/Monodomain3dRabbitHeart`.

**Comment by finsberg** [comment]
Perfect!
