### ISSUE TITLE
#2905 - Update Wiki in light of switch to Git and CMake

### ISSUE THREAD

**Issue by kwabenantim** [Chaste/Chaste#40]
This issue continues the discussion for legacy trac ticket 2905:

---
[fcooper8472](https://github.com/orgs/Chaste/people/fcooper8472) created the following ticket on 2017-05-18 at 13:53:53, it is owned by [fcooper8472](https://github.com/orgs/Chaste/people/fcooper8472)

Prior to Release 17.4, we need to update the wiki in light of several major changes:

* Svn -> Git: Remove all references to accessing the svn repo
* CMake -> Scons: Indicate that CMake is now preferred, but that Scons is deprecated but still working

The goal is that, by clicking through links from the [front page](https://chaste.cs.ox.ac.uk/trac/wiki) it should be impossible to access defunct instructions without it being obvious they are defunct!

Old versions of pages that we will never want to change can be linked to from under SconsArchive (like old AttendancePlan are listed). But if there's even a chance the scons way of working will be modified (for c++11 etc.) we may still need to update them, and so we'll need live wiki pages: in this case they should be copied to new wiki pages under SconsArchive. N.B. you can rename wiki pages to move them under SconsArchive using button at the bottom of the pages.

* <s>GettingStarted (update figure etc.)</s>
* ChasteGuides <s>(remove info on cardiac executable?)</s>
    * <s>ChasteGuides/HostconfigSystem (new guide for when cmake doesn't pick them up?)</s>
    * <s>ChasteGuides/RunningFirstTests</s>
    * <s>ChasteGuides/VisualisationGuides/CombineConsecutiveSimulations</s>
    * ChasteGuides/RunningAcceptanceTests (may not be necessary - see [trac ticket 2908])
    * <s>ChasteGuides/RunningBinariesFromCommandLine</s>
* <s>InstallGuides/InstallGuide (bottom bit).</s>
* <s>InstallGuides/Arc#GettingChaste</s>
* MakingARelease
* <s>UserTutorials (scons at the top)</s>
* <s>Something on building executables in `apps` folders (moved scons instructions to SconsArchive/BuildingCardiacExecutable - which also applied to projects etc.)</s>
* <s>The 'default repository' on here https://chaste.cs.ox.ac.uk/trac/browser is confusing since it is the old defunct one. I have navigated to out of date trunk files by looking at it a few times.</s>
* <s>These files needs updating:</s>
    *<s>https://chaste.cs.ox.ac.uk/trac/browser/git_repo/projects/README should probably point at a relevant wiki page.</s>
    * <s>https://chaste.cs.ox.ac.uk/trac/browser/git_repo/README.txt</s>

etc. etc.

---
Comment by [fcooper8472](https://github.com/orgs/Chaste/people/fcooper8472) on 2017-05-19 at 15:06:10

[GettingStarted](https://chaste.cs.ox.ac.uk/trac/wiki/GettingStarted) is now up-to-date.  Please make changes/edit as you see fit.

---
Comment by [fcooper8472](https://github.com/orgs/Chaste/people/fcooper8472) on 2017-05-31 at 15:56:25

* <s>`done` GettingStarted (update figure etc.)</s>
* <s>`done` [ChasteGuides] (remove info on cardiac executable?)</s>
* <s>`done` ChasteGuides/RunningFirstTests (ChasteGuides/CmakeFirstRun)</s>
* <s>`done` InstallGuides/InstallGuide (bottom bit).</s>
* <s>`done` UserTutorials (scons at the top)</s>
* <s>`done` ChasteGuides/VisualisationGuides/CombineConsecutiveSimulations</s>

* <s>ChasteGuides/HostconfigSystem (new guide for when cmake doesn't pick them up?)</s>
    * There is already extensive information on how to specify dependency locations, in the ChasteGuides/CmakeBuildGuide, so I think this can be considered `done` too.

* <s>Something on building executables in `apps` folders (moved scons instructions to SconsArchive/BuildingCardiacExecutable - which also applied to projects etc.)</s>
    * Also already in the ChasteGuides/CmakeBuildGuide ([here](https://chaste.cs.ox.ac.uk/trac/wiki/ChasteGuides/CmakeBuildGuide#BuildingProjects)), so also considered `done`.

* MakingARelease
    * Need to decide which bits to keep, and which bits to remove.  Perhaps worth a dedicated ticket?

* InstallGuides/Arc#GettingChaste
    * Could do with someone in a position to fiddle with this.  Maybe James Grogan?

---
Comment by [mirams](https://github.com/orgs/Chaste/people/mirams) on 2017-06-01 at 10:40:31

I think the information on:

* setting up dependency locations
* building executables
* running acceptance tests on executables

would be better on three dedicated wiki pages (updating/replacing/renaming ChasteGuides/HostconfigSystem; ChasteGuides/BuildingCardiacExecutable; ChasteGuides/RunningAcceptanceTests respectively) to make CmakeBuildGuide less of an overwhelming monster sized page.

The CmakeBuildGuide needs a bit of reading with a novice hat on, for a lot of our users this might be the first c++ project they have built from source using cmake. When we say things like *"You can specify a Boost directory by using the BOOST_ROOT CMake variable"* or *"You can specify a Sundials folder by setting the SUNDIALS_ROOT environment variables"* it would be much better to give things to type on the command line. Similarly we need to explain what *"install the Chaste libraries"*, *"Packaging your build"* mean (I don't know what this last one means!).

Perhaps we can put a bit of the expert stuff on a ChasteGuides/CmakeAdvancedBuildGuide? things like `make tutorials` are going to understandably cause confusion if listed in the users' CmakeBuildGuide.

---
Comment by [fcooper8472](https://github.com/orgs/Chaste/people/fcooper8472) on 2017-06-01 at 13:26:43

ChasteGuides/BuildingExecutableApps now exists.

---
Comment by [fcooper8472](https://github.com/orgs/Chaste/people/fcooper8472) on 2017-06-01 at 14:06:56

There is now a ChasteGuides/FindingChasteDependencies, and the relevant information has been moved over from the Cmake Build Guide.

---
Comment by [fcooper8472](https://github.com/orgs/Chaste/people/fcooper8472) on 2017-06-01 at 14:35:30

I have changed the default repository on trac.

If you go to the [browse source tab](https://chaste.cs.ox.ac.uk/trac/browser) now, you should see the main git repo.

---
Comment by [mirams](https://github.com/orgs/Chaste/people/mirams) on 2017-06-01 at 14:42:43

Replying to [fcooper](comment:17):
> I have changed the default repository on trac.
>
> If you go to the [browse source tab](https://chaste.cs.ox.ac.uk/trac/browser) now, you should see the main git repo.
This does mean that all links to svn changesets are broken though - any way to automatically mend the existing links (change `rXXXX` to `[rXXXX](changeset:XXXX/svn_repo)` sort of thing)?

---
Comment by [fcooper8472](https://github.com/orgs/Chaste/people/fcooper8472) on 2017-06-01 at 14:58:46

Replying to [GaryM](comment:18):
> Replying to [fcooper](comment:17):
> > I have changed the default repository on trac.
> >
> > If you go to the [browse source tab](https://chaste.cs.ox.ac.uk/trac/browser) now, you should see the main git repo.
> This does mean that all links to svn changesets are broken though - any way to automatically mend the existing links (change `rXXXX` to `[rXXXX](changeset:XXXX/svn_repo)` sort of thing)?

Agh, that's a massive pain...

It *might* be possible to add some functionality to `TracWebUtils.py` or `TracDbUtils.py` to crawl every page on the wiki and do some regex magic.
Sounds dangerous though!  Not to mention I'm not sure how one would deal with tickets, which would be the main issue.

Any ideas?

---
Comment by [mirams](https://github.com/orgs/Chaste/people/mirams) on 2017-06-01 at 15:04:13

I'm tempted to say it's not too hard to copy the revision number into the search box and get where you need to fairly fast, since most 'active' work will now be on git repo, and using that will be much easier (won't need the `/git_repo` for that presumably any more?). But we should probably check with everyone else on slack #general or something.

---
Comment by [fcooper8472](https://github.com/orgs/Chaste/people/fcooper8472) on 2017-06-05 at 10:53:41

Just to take stock, the following aren't crossed out yet:

Guides:

* ChasteGuides/RunningAcceptanceTests (Input from Joe? - see [trac ticket 2908])
* ChasteGuides/RunningBinariesFromCommandLine

* InstallGuides/Arc#GettingChaste (Looks as though James is adding things right now)
* MakingARelease (Could  do with Gary and Joe in the same room for few mins)

---
Comment by [fcooper8472](https://github.com/orgs/Chaste/people/fcooper8472) on 2017-06-05 at 11:21:51

ChasteGuides/RunningBinariesFromCommandLine is now up-to-date.

---
Comment by [jmsgrogan](https://github.com/jmsgrogan) on 2017-06-05 at 12:51:36

I've updated InstallGuides/Arc and moved the old Scons instructions into the archive. I've only had a chance to test this on Arcus-B, but have pointed to the old Scons guide for things that might be different on Arcus (A).

**Comment by fcooper8472** [comment]
Closing: all remaining work is covered by website migration
