### ISSUE TITLE
Get Docker support for apple m series processors

### ISSUE THREAD

**Issue by fieldofnodes** [Chaste/Chaste#43]
Please see the [guides](https://chaste.cs.ox.ac.uk/trac/wiki/ChasteGuides), and [discussions](https://github.com/Chaste/Chaste/discussions) for answers to common problems.

**Describe the bug**
I tried to run the docker chaste on an apple mac with an M1 chip.  The current docker is setup to do this.

Can I get confirmation of this?

If so, when or how should we go about spinning that up?

**To Reproduce**
Steps to reproduce the problem.

```
git clone --recursive https://github.com/Chaste/Chaste.git chaste
cd chaste
mkdir build
cmake ..
```

```
CMake Error: The source directory does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Expected behavior**

**System**
Please provide relevant details of your system, such as:
 * OS version
 * CMake version
 * C++ compiler version
 * Python version
 * Relevant Chaste dependency versions e.g. PETSc, Boost, Sundials etc.

Some of this information can be generated by running `TestChasteBuildInfo`:
```
git clone --recursive https://github.com/Chaste/Chaste.git chaste
cd chaste
mkdir build
cd build
cmake ..
cmake --build . --target TestChasteBuildInfo
ctest -V -R TestChasteBuildInfo
```

Please paste the full output in a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks). It will be similar to the truncated example below. 
```
6:  ***** TestChasteBuildInfo.hpp *****
6: Entering TestShowInfo
6: <ChasteBuildInfo>
.
.
.
6: </ChasteBuildInfo>
6: Passed
6: OK!
1/1 Test #6: TestChasteBuildInfo ..............   Passed    2.38 sec

```

**Additional context**
Include additional information about the problem here if relevant.

**Screenshots**

**Comment by mirams** [comment]
Hi @fieldofnodes the cmake error above looks to be due to running cmake on the folder above the Chaste source if you followed those steps:
>
```
git clone --recursive https://github.com/Chaste/Chaste.git chaste
cd chaste
mkdir build
cmake ..
```

**Comment by jmpf** [comment]
Server Lofty is being prepared for becoming a testing machine.

Fergus had did a partial upgrade to 20.04 the other week.  I've been working on it today.  In order to stabilise I had to 

- Upgrade/break libgoogleperftools
- Replace the edited ssh config file with the new one for 22.04
- Remove buildbot and python3-buildbot packages which couldn't be configured and were blocking the upgrade

Once down, the upgrade from 20.04 to 22.04 went without a snag.
Todo: Investigate the above points and reinstall HFS backup software

**Comment by bdevans** [comment]
PR #157 automatically builds `chaste/develop` images for both `amd` and `arm` architectures. This will be complete once that is merged.

**Comment by bdevans** [comment]
PR #157 has been merged and is working! 🥳  This issue can therefore be closed unless there are other unresolved points, in which case it might be better renaming it.

**Comment by fieldofnodes** [comment]
I'll give it a crack and update for the close.

**Comment by fieldofnodes** [comment]
Hi, how exactly do I run the chaste that can work on M1, is it chaste/release or chaste/develop?

**Comment by bdevans** [comment]
Currently only `chaste/develop` is built for `arm` and `amd` processors. The next release will be built for both.
