### ISSUE TITLE
Fix Nightly Continuous -np3 testsuite TestPetscTools

### ISSUE THREAD

**Issue by jmpf** [Chaste/Chaste#47]
**Describe the bug**
The test suite TestPetscTools fails when run on more modern versions of PETSc.  See
https://chaste.cs.ox.ac.uk/buildbot/builders/Nightly%20Continuous%20np3

**To Reproduce**
Configure with -DChaste_NUM_CPUS_TEST=3 and PETSc 3.12 and run the test suite.
Alternatively see https://github.com/Chaste/dependency-modules/actions/runs/3445084906/jobs/5748389962

In November 2022 Kwabena narrowed this down to PETSc 3.11:
PETSc Version | Parallel Test Result
3.7.7 | Pass
3.8.4 | Pass
3.9.4 | Pass
3.10.5 | Pass
3.11.3 | Fail
3.12.4 | Fail
3.13.6 | Fail
3.14.6 | Fail
3.15.5 | Fail
3.16.6 | Fail

**Diagnosis**
As of November I thought thought that this was a bug in PETSc from 3.11 onwards.  The bug is manifest by a failure to obey the directions in the ``MatMPIAIJSetPreallocation`` function on the processes which get ranks 1 or 2 in a parallel run.  My action was to distil the problem into a minimal PETSc test (that passes 3.10 but fails 3.11) and then report it as a PETSc bug.

However, now that I have written a minimal test, I find that it's unable to reproduce the error.  More investigation is needed to bring the failing test from TestPetscTools closer to the non-failing minimal test.

**Comment by jmpf** [comment]
Here's an idea of what I've been doing to reproduce the bug.

[NonzeroAllocation.cpp.txt](https://github.com/Chaste/Chaste/files/10394518/NonzeroAllocation.cpp.txt)
[Makefile.txt](https://github.com/Chaste/Chaste/files/10394522/Makefile.txt)

**Comment by jmpf** [comment]
I am now able to reproduce the bug.  This can be done by allocating more nonzeros on the block diagonal (and fewer on the offdiagonal).  The original test has `` MatMPIAIJSetPreallocation(A, 4, PETSC_NULL, 4, PETSC_NULL); `` and produces output:
### PETSc 3.6

> 1: 3 rows owned => 24 nonzeros expected. 24 actually allocated. True
> 2: 3 rows owned => 24 nonzeros expected. 24 actually allocated. True
> 0: 4 rows owned => 32 nonzeros expected. 32 actually allocated. True


### PETSc 3.12
> 1: 3 rows owned => 24 nonzeros expected. 21 actually allocated. False
> 2: 3 rows owned => 24 nonzeros expected. 21 actually allocated. False
> 0: 4 rows owned => 32 nonzeros expected. 32 actually allocated. True

**Comment by jmpf** [comment]
Systematic parameter sweep:

| d_nz requested  | o_nz requested         | P0 non-zeros per row (owns 4 rows)| P1&2 non-zeros per row (owns 3 rows)|
| --------- |-------------| ------|----|
|0|8|8|8|
|1|7|8|8|
|2|6|8|8|
|3|5|8|8|
|4|4|8|7|
|5|3|7|6|
|6|2|6|5|
|7|1|5|4|
|8|0|4|3|


There's a simple formula to see what is happening here:
> nz_allocated per row = min(d_nz, rows_owned) + o_nz

Since there the block diagonal part of the matrix is square, it only has rows_owned*rows_owned entries.  That is, it doesn't make sense to allocate more than rows_owned non-zeros per row of the block diagonal.

### Conclusion
The change in PETSc 3.11 is not a bug but rather a feature to prevent over-allocating space in the matrix.

**Comment by mirams** [comment]
Ah, that's good, all makes sense! So our tests need an update and new PETSc being more sensible.

**Comment by jmpf** [comment]
Yes.  I'll make a fix in due course.

**Comment by jmpf** [comment]
Rather nastily the actual test was on a non-square matrix (12x10).  In this case the number of local rows won't match with the number of columns in the block diagonal.  We could do the arithmetic for this (by asking PETSc how it splits a Vec sized by the number of columns).  However I think that the square case is a sufficient test.

**Comment by jmpf** [comment]
Bug fixed.  See https://chaste.cs.ox.ac.uk/buildbot/builders/Nightly%20Continuous%20np3/builds/1572
