### ISSUE TITLE
migrate tutorial generation from buildbot to github actions

### ISSUE THREAD

**Issue by martinjrobins** [Chaste/Chaste#55]
See #50. Tutorials are currently uploaded to wiki - plan is to move these to the website instead

**Comment by mirams** [comment]
See also the https://chaste.cs.ox.ac.uk/trac/wiki/ChasteGuides/HowTo page which also reads code comments and makes a wiki page from them

**Comment by fcooper8472** [comment]
I didn't know these existed!

@mirams do you know which code did this? And how/when it got updated?

**Comment by mirams** [comment]
Well there’s `GenerateHowTo.py` in the infrastructure scripts repo, but basically worked the same as the tutorial generation in terms of being called, reading code comments, writing trac markdown.

**Comment by fcooper8472** [comment]
@mirams I've opened a new issue for the how-tos: #185

**Comment by fcooper8472** [comment]
This is progressing well: the tutorials are currently on the new website, here:
https://chaste.github.io/docs/user-tutorials/

They are not yet publicly linked-to from anywhere on the website, as there are still some tweaks that need to be applied.

The strategy is to:

- [x] Update the tutorials themselves so they more-closely resemble markdown
- [x] Reduce the level of the headings (e.g. starting from ## not #, more in keeping with the website)
- [x] Tweak the website for better formatting: wider page, or smaller font, so there is less sideways scroll

**Comment by fcooper8472** [comment]
Possibly useful for any other changes in future: a quick-and-dirty regex find-and-replace for inline code blocks:

```python
def regex_find_and_replace(file_path: Path):

    pattern_to_find = re.compile(r"(.*){{{(.+)}}}(.*)$")

    # Open the file and read line by line
    lines = []
    with file_path.open('r', encoding='utf-8') as file:
        for line in file:
            if re.match(pattern_to_find, line):
                # Perform the regex substitution for each line
                new_line = pattern_to_find.sub(
                    lambda match: match.group(1) + '`' + match.group(2) + '`' + match.group(3), line
                )
                lines.append(new_line)
                print(f'~~~{line}~~~\n%%%{new_line}%%%\n')
            else:
                lines.append(line)

    # Write the modified lines back to the file, overwriting the old one
    with file_path.open('w', encoding='utf-8') as file:
        file.writelines(lines)
```

and for headings:

```python
def regex_find_and_replace(file_path: Path):
    pattern_to_find = re.compile(r"([ *\/]*)(=+)(.+)\2\s*$")

    # Open the file and read line by line
    lines = []
    with file_path.open('r', encoding='utf-8') as file:
        for line in file:
            if re.match(pattern_to_find, line):
                # Perform the regex substitution for each line
                new_line = pattern_to_find.sub(
                    lambda match: match.group(1) + '#' * (1+len(match.group(2).strip())) + ' ' + match.group(3).strip() + '\n', line
                )
                lines.append(new_line)
            else:
                lines.append(line)

    # Write the modified lines back to the file, overwriting the old one
    with file_path.open('w', encoding='utf-8') as file:
        file.writelines(lines)
```
