### ISSUE TITLE
Possible missmatch between boost version causes TestArchiveFromat to fail

### ISSUE THREAD

**Issue by BJackal** [Chaste/Chaste#57]
Please see the [guides](https://chaste.cs.ox.ac.uk/trac/wiki/ChasteGuides), and [discussions](https://github.com/Chaste/Chaste/discussions) for answers to common problems.

**Describe the bug**
When merging develop into an older branch (auatay_ticket_2987_ode_edges) once correcting all conflicts and issues the only Continuous test to fail is TestArchiveFormat to fail. Determined that this is specifically to the following files:

cell_population_sim_at_time_150.arch
cell_population_sim_at_time_150.arch.0
mesh_150.edge
mesh_150.ele
mesh_150.ncl
mesh_150.node

This issue can be corrected by re-running TestGenerateSteadyStateCrypt and then copying the corresponding output files back into the correct crypt location.

**To Reproduce**
Steps to reproduce the problem.

```
** Assuming here user is already on the development branch and has correctly built Chaste**
cd chaste

git checkout 
git checkout auatay_ticket_2987_ode_edges
cd build
make -j4 Continuous  
ctest -j4 -L Continuous  
** All tests here will pass except for TestArchiveFormat **
** Then Wed do the following to correct it **

make TestGenerateSteadyStateCrypt
ctest -R TestGenerateSteadyStateCrypt
cp /tmp/$USER/testoutput/SteadyStateCrypt/archive/?*_150.* ../crypt/test/data/SteadyStateCrypt/archive/

make -j4 Continuous  
ctest -j4 -L Continuous  
** TestArchiveFromat will now pass**


**Expected behavior**
TestArchiveFormat should pass with no errors but instead is unable to even run properly.

**System**
Please provide relevant details of your system, such as:
Ubuntu 18.04.6 LTS
cmake version 3.24.1

**Comment by BJackal** [comment]
@jmpf

**Comment by jmpf** [comment]
https://github.com/Chaste/Chaste/blob/develop/crypt/test/simulation/TestArchiveFormat.hpp#L82

**Comment by BJackal** [comment]
Thanks Joe, Ill give that a go and see if it fixes the issues !
