### ISSUE TITLE
Create private Chaste repo with associated wiki

### ISSUE THREAD

**Issue by AlexFletcher** [Chaste/Chaste#59]

**Comment by AlexFletcher** [comment]
See [here](https://docs.google.com/document/d/1_Rhs_f8GHJLQLJ63wfSG9C1NneAz-EEqA4ktAQ9Lw68/edit?usp=sharing) for a list of old wiki pages. We will annotate those pages that should be moved to the public Chaste website and those which should be moved to the private developer wiki. If you don't have access to the google doc and think you should have, then contact me.

**Comment by AlexFletcher** [comment]
In the google doc linked to in my above comment, I've now colour coded those wiki pages that I *think* should be copied over to either the new public Chaste website or to the new private developer wiki. Please could someone (@fcooper8472 @mirams @jmpf ?) take a quick look through and either let us know if they agree, or amend as necessary.

**Comment by mirams** [comment]
Looks good to me, tweaked a couple

**Comment by AlexFletcher** [comment]
Thanks @mirams. Any comments @fcooper8472 @jmpf or anyone else?

**Comment by jmpf** [comment]
Read it and it looks reasonable.

I'd quite like an archive of stuff like BuildServerSetup, but I think that archiving the entire wiki somewhere safe before it dies is the way to do it.

**Comment by fcooper8472** [comment]
@jmpf the entire archive already exists.  See, e.g. [here](https://github.com/Chaste/trac_archive/wiki/Build-Server-Setup) for the page you mentioned.

**Comment by mirams** [comment]
Be nice to get all the wiki links working, the top one there does but the rest (nested under InstallGuides/* ??) don't seem to be working?

**Comment by fcooper8472** [comment]
Yes, that should be fairly straightforward to fix. This is just down to the fact that GitHub wiki page titles are determined by their file names.

Fix (hopefully...) incoming.

**Comment by fcooper8472** [comment]
@mirams I've got a fix ready for a lot of the links, but there are quite a few that don't seem to make any sense.

I'll wait to push these changes until I can get back into the old wiki to investigate what the links originally looked like.

**Comment by fcooper8472** [comment]
Ah - think I see what's happened.  Links to class names in tutorials etc have been erroneously changed to wiki links. That's a bit of a pain!

**Comment by fcooper8472** [comment]
@mirams and @jmpf this should now all be resolved.

The class names now direct to the appropriate public docs page (e.g. https://chaste.cs.ox.ac.uk/public-docs/classAbstractForce.html) and the genuine wiki links should all now work.

Could you have a poke around and let me know if anything still isn't working as expected?

**Comment by fcooper8472** [comment]
Ah. Relative links are also all broken because the new wiki is flat. This affects things like:
https://github.com/Chaste/trac_archive/wiki/Install-Guides

that has a link that ought to go to:
https://github.com/Chaste/trac_archive/wiki/Install-Guides-_-Dependency-Versions

I'm working on a fix, but it's going to be a bit trickier than the rest.

**Comment by fcooper8472** [comment]
Turned out to be easier than expected.

Let me know if anything else looks like it's not working.

**Comment by MauriceHendrix** [comment]
@fcooper8472 where have we got to with the public wiki? I'd like to link to cmake instructions, but don't want the link to be invalid shortly.

**Comment by fcooper8472** [comment]
It's coming along, but it's one of those annoying things where if I put some of it up there will be dangling links and a general mess.

I'll prioritise getting it into a useful state.
