### ISSUE TITLE
Broken link on download?

### ISSUE THREAD

**Issue by SimonHettrick** [Chaste/Chaste#6]
I just tried to download Chaste. The page that pops up (https://www.cs.ox.ac.uk/chaste/download.html) has a section at the bottom stating:

"Redirect to GitHub
Please see the [tagged release on GitHub](https://github.com/Chaste/Chaste/releases/tag/2019.1) and download from there. Thank you."

I get a 404 on the link it provides. I think the correct link is: https://github.com/Chaste/Chaste/releases/tag/release_2019.1

**Comment by fcooper8472** [comment]
Thanks @SimonHettrick, you're right, that is the correct link.

@jmpf I think you're the only one with permissions to update the website.

**Comment by jmpf** [comment]
Thanks Simon.
I'd prefer this to go to the parent page https://github.com/Chaste/Chaste/releases/ since Github should always promote the tagged releases in reverse chronological order.

**Comment by jmpf** [comment]
Fixed now.  It's a direct link to the tagged release because the download form (which ought to be gracefully deprecated) allows users to select previous releases.
