### ISSUE TITLE
ParaView 5.10 GlyphLegacy Issues in PSVM files

### ISSUE THREAD

**Issue by fieldofnodes** [Chaste/Chaste#66]
Hi,

I am not sure if this is the place to ask, but I am running chaste from the docker image and using a project,  In this project I have a psvm file to load the specific geometries.
[paraview_error.txt](https://github.com/Chaste/Chaste/files/10775389/paraview_error.txt)

When I did this in an older version of para

view, I had no problems (version 5.6 had some warnings, but still worked), Now these warning have become errors.

Please see the attached file.

[paraview_error.txt](https://github.com/Chaste/Chaste/files/10775390/paraview_error.txt)

Is there a straightforward action that I need to take to fix this problem or is it more involved?

**Comment by jmpf** [comment]
What is the file (from Chaste) that you are loading into Paraview and how was it created?  Thanks.

**Comment by mirams** [comment]
Any update @fieldofnodes ? Just doing a ticket audit...

**Comment by fieldofnodes** [comment]
Fixed. Not sure if my fix was the right one, but I downloaded every version of Paraview since the one I started with re-saved my `.pvsm` file. That incrementally updated things. All good now.
