### ISSUE TITLE
CellML files as submodule or with cmake_fetch

### ISSUE THREAD

**Issue by MauriceHendrix** [Chaste/Chaste#70]
@mirams lest us know what you think.
yesterday in the meeting I asked for --recursive to be added in the automated testing script, so cellml files could be included from the cellml repo. However @fcooper8472 didn't like this idea bcause even if you provide instructions many people just copy-paste from gitub and it would break stuff. As an alternative he suggested using cmake_fecth. 

I have just been trying this out and it works by downloading the cellml files at build time into the build folder.
The implcations of this as far as I can see:
- You would need internet when building (but that's already true due to codegen being installed at that point)
- It's possible to pin to the current master branch, I guess we'd want that? If not pinning to a certain commit is possible too.
- The test needs to switch to finding the cellml file relative to build folder (no big deal)
- It's worth noting that the oxmeta ontology doesn't get included anymore since the switch to codegen, it's included in the codegen installation, so there are currently no other submodules.

**Comment by mirams** [comment]
I think I didn't realise that the ontology submodule had disappeared into chaste_codegen.

**Comment by mirams** [comment]
For reproducibility we probably need to pin to a given commit of Chaste/cellml, otherwise we won't know exactly what files were being tested without lots of looking at timestamps etc.

**Comment by mirams** [comment]
And add lots of documentation at the top of all the relevant tests to say how to change that commit!

**Comment by fcooper8472** [comment]
Just a couple of things to add:

- Changing the commit is straightforward, [here's an example where I've used it for a different project](https://github.com/PalamaraLab/PrepareDecoding/blob/046495da3739b27b9d3bbf2b12eb147e7aea4de4/test/CMakeLists.txt#L9)
- It only gets fetched once per configuration, not per build, so it won't get endlessly getting it each time you re-build

The downside, in fairness, is that the data will be retrieved more often than if it were a submodule as you may well work with multiple configurations.

@MauriceHendrix how much data are we talking about?

**Comment by MauriceHendrix** [comment]
> Just a couple of things to add:
> 
> * Changing the commit is straightforward, here's an example where I've used it for a different project
> * It only gets fetched once per configuration, not per build, so it won't get endlessly getting it each time you re-build
> 
> The downside, in fairness, is that the data will be retrieved more often than if it were a submodule as you may well work with multiple configurations.
> 
> @MauriceHendrix how much data are we talking about?

about 19MB

**Comment by fcooper8472** [comment]
Given it's not much data, my personal opinion would be to get this through CMake FetchContent.
