### ISSUE TITLE
Eclipse settings

### ISSUE THREAD

**Issue by MauriceHendrix** [Chaste/Chaste#74]
In the folder eclipse settings we seem to have some rather old settings for the eclipse IDE. I'm coming across these as I'm trying to remove references to SCons (#73 ).

I'm just wondering if we need to keep these clipse settings, I don't think they actually work or have been used by anywabody in a while. What do people think?

**Comment by mirams** [comment]
Happy to get rid of these, I think we're all on VSCode or more modern things these days?

**Comment by MauriceHendrix** [comment]
> Happy to get rid of these, I think we're all on VSCode or more modern things these days?

@AlexFletcher agree?

**Comment by AlexFletcher** [comment]
Yes I agree!

**Comment by jmpf** [comment]
./eclipse_settings was deleted as part of PR #73 on April 4.

**Comment by jmpf** [comment]
That left the .project file (which is also eclipse specific).  I deleted this in develop@b7ee62a.

Note that a simple deletion via the web interface allowed me to bypass peer review.
